"""Stable classifications for the deterministic A2.9 benchmark."""

from enum import StrEnum


class BaselineDirection(StrEnum):
    """Direction inferred from independently retained opposing evidence."""

    POSITIVE = "POSITIVE"
    NEGATIVE = "NEGATIVE"
    NEUTRAL = "NEUTRAL"
    CONFLICTED = "CONFLICTED"


class CandidateClass(StrEnum):
    """Transparent benchmark class, never an order or recommendation."""

    TOP_MOVER = "TOP_MOVER"
    EARLY_OPPORTUNITY = "EARLY_OPPORTUNITY"
    MATURE_AVOID_CHASE = "MATURE_AVOID_CHASE"
    NO_TRADE = "NO_TRADE"


class ComponentName(StrEnum):
    """Decomposable baseline component families."""

    DIRECTIONAL_STRUCTURE = "DIRECTIONAL_STRUCTURE"
    TREND_QUALITY = "TREND_QUALITY"
    MOMENTUM = "MOMENTUM"
    RELATIVE_STRENGTH = "RELATIVE_STRENGTH"
    PARTICIPATION = "PARTICIPATION"
    STRUCTURAL_READINESS = "STRUCTURAL_READINESS"
    VOLATILITY_SUITABILITY = "VOLATILITY_SUITABILITY"
    REMAINING_ROOM = "REMAINING_ROOM"
    EXTENSION_CHASE_RISK = "EXTENSION_CHASE_RISK"
    MULTI_TIMEFRAME_ALIGNMENT = "MULTI_TIMEFRAME_ALIGNMENT"
    DERIVATIVES_CONTEXT = "DERIVATIVES_CONTEXT"


class BaselineEvidenceSource(StrEnum):
    """Explicit evidence slots accepted by the provider-neutral request."""

    PRIMARY = "PRIMARY"
    INDICATOR = "INDICATOR"
    RELATIVE = "RELATIVE"
    MULTI_TIMEFRAME = "MULTI_TIMEFRAME"
    DERIVATIVES = "DERIVATIVES"


class RuleRole(StrEnum):
    """How a transformed fact participates in a component."""

    DIRECTIONAL = "DIRECTIONAL"
    SUITABILITY = "SUITABILITY"
    PENALTY = "PENALTY"


class ScoreSemantics(StrEnum):
    """Public interpretation of a component's main score."""

    DIRECTIONAL_SUPPORT = "DIRECTIONAL_SUPPORT"
    SUITABILITY = "SUITABILITY"
    PENALTY = "PENALTY"


class TransformKind(StrEnum):
    """Small, monotonic, policy-parameterized transforms."""

    SIGNED_LINEAR = "SIGNED_LINEAR"
    CENTERED_LINEAR = "CENTERED_LINEAR"
    UNSIGNED_LINEAR = "UNSIGNED_LINEAR"
    TRIANGLE = "TRIANGLE"
    LOWER_BETTER = "LOWER_BETTER"
    POSITIVE_ROOM = "POSITIVE_ROOM"
    NEGATIVE_ROOM = "NEGATIVE_ROOM"


class ExplanationCode(StrEnum):
    """Deterministic facts and gates used by the initial policy."""

    POSITIVE_STRUCTURE = "POSITIVE_STRUCTURE"
    NEGATIVE_STRUCTURE = "NEGATIVE_STRUCTURE"
    POSITIVE_SLOPE = "POSITIVE_SLOPE"
    NEGATIVE_SLOPE = "NEGATIVE_SLOPE"
    ABOVE_EMA20 = "ABOVE_EMA20"
    BELOW_EMA20 = "BELOW_EMA20"
    POSITIVE_MOMENTUM = "POSITIVE_MOMENTUM"
    NEGATIVE_MOMENTUM = "NEGATIVE_MOMENTUM"
    RELATIVE_OUTPERFORMANCE = "RELATIVE_OUTPERFORMANCE"
    RELATIVE_UNDERPERFORMANCE = "RELATIVE_UNDERPERFORMANCE"
    POSITIVE_PARTICIPATION = "POSITIVE_PARTICIPATION"
    NEGATIVE_PARTICIPATION = "NEGATIVE_PARTICIPATION"
    NEAR_PRIOR_HIGH = "NEAR_PRIOR_HIGH"
    NEAR_PRIOR_LOW = "NEAR_PRIOR_LOW"
    RANGE_COMPRESSED = "RANGE_COMPRESSED"
    BREAKOUT_EXCURSION = "BREAKOUT_EXCURSION"
    BREAKDOWN_EXCURSION = "BREAKDOWN_EXCURSION"
    VOLATILITY_USABLE = "VOLATILITY_USABLE"
    POSITIVE_ROOM_AVAILABLE = "POSITIVE_ROOM_AVAILABLE"
    NEGATIVE_ROOM_AVAILABLE = "NEGATIVE_ROOM_AVAILABLE"
    LOW_REMAINING_ROOM = "LOW_REMAINING_ROOM"
    HIGH_EXTENSION = "HIGH_EXTENSION"
    MTF_ALIGNED = "MTF_ALIGNED"
    MTF_MIXED = "MTF_MIXED"
    MTF_CONFLICTED = "MTF_CONFLICTED"
    MTF_POSITIVE_EVIDENCE = "MTF_POSITIVE_EVIDENCE"
    MTF_NEGATIVE_EVIDENCE = "MTF_NEGATIVE_EVIDENCE"
    MTF_AGREEMENT_EVIDENCE = "MTF_AGREEMENT_EVIDENCE"
    MTF_DISAGREEMENT_EVIDENCE = "MTF_DISAGREEMENT_EVIDENCE"
    DERIVATIVES_LIQUIDITY_USABLE = "DERIVATIVES_LIQUIDITY_USABLE"
    EVIDENCE_PARTIAL = "EVIDENCE_PARTIAL"
    EVIDENCE_DEGRADED = "EVIDENCE_DEGRADED"
    EVIDENCE_MISSING = "EVIDENCE_MISSING"
    EVIDENCE_STALE = "EVIDENCE_STALE"
    EVIDENCE_AGING = "EVIDENCE_AGING"
    DIRECTION_NEUTRAL = "DIRECTION_NEUTRAL"
    DIRECTION_CONFLICTED = "DIRECTION_CONFLICTED"
    BELOW_OPPORTUNITY_THRESHOLD = "BELOW_OPPORTUNITY_THRESHOLD"
    ALIGNMENT_BELOW_THRESHOLD = "ALIGNMENT_BELOW_THRESHOLD"
    MATURE_EXTENSION = "MATURE_EXTENSION"
    MATURE_LOW_ROOM = "MATURE_LOW_ROOM"
