"""Version 1.0 engineering policies for the deterministic benchmark."""

from tiaf.contracts import DataQuality, TradeStyle

from .enums import (
    BaselineEvidenceSource as Source,
)
from .enums import (
    ComponentName as Component,
)
from .enums import (
    ExplanationCode as Code,
)
from .enums import (
    RuleRole as Role,
)
from .enums import (
    TransformKind as Transform,
)
from .errors import BaselinePolicyError
from .models import (
    BaselinePolicy,
    ClassificationThresholds,
    ComponentWeight,
    DirectionThresholds,
    EvidenceRule,
    EvidenceSelector,
    PenaltyPolicy,
    QualityFactor,
)


def _selector(
    source: Source,
    evidence_id: str,
    parameters: tuple[tuple[str, int], ...] = (),
    output_name: str | None = None,
) -> EvidenceSelector:
    return EvidenceSelector(
        source=source,
        evidence_id=evidence_id,
        parameters=parameters,
        output_name=output_name,
    )


def _rule(
    rule_id: str,
    component: Component,
    source: Source,
    evidence_id: str,
    role: Role,
    transform: Transform,
    weight: float,
    *,
    parameters: tuple[tuple[str, int], ...] = (),
    output_name: str | None = None,
    required: bool = False,
    orientation: int = 1,
    scale: float | None = None,
    center: float | None = None,
    floor: float | None = None,
    target: float | None = None,
    ceiling: float | None = None,
    post_boundary_credit: float = 0.0,
    code_threshold: float = 0.0,
    positive_code: Code | None = None,
    negative_code: Code | None = None,
) -> EvidenceRule:
    return EvidenceRule(
        rule_id=rule_id,
        component=component,
        selector=_selector(source, evidence_id, parameters, output_name),
        role=role,
        transform=transform,
        weight=weight,
        required=required,
        orientation=orientation,
        scale=scale,
        center=center,
        floor=floor,
        target=target,
        ceiling=ceiling,
        post_boundary_credit=post_boundary_credit,
        code_threshold=code_threshold,
        positive_code=positive_code,
        negative_code=negative_code,
    )


def _component_weights(style: TradeStyle) -> tuple[ComponentWeight, ...]:
    if style is TradeStyle.DAY:
        values = (
            (Component.DIRECTIONAL_STRUCTURE, 0.17, 0.10, True),
            (Component.TREND_QUALITY, 0.18, 0.12, True),
            (Component.MOMENTUM, 0.18, 0.12, True),
            (Component.RELATIVE_STRENGTH, 0.10, 0.08, False),
            (Component.PARTICIPATION, 0.14, 0.14, False),
            (Component.STRUCTURAL_READINESS, 0.10, 0.16, False),
            (Component.VOLATILITY_SUITABILITY, 0.0, 0.11, False),
            (Component.REMAINING_ROOM, 0.0, 0.09, False),
            (Component.EXTENSION_CHASE_RISK, 0.0, 0.0, False),
            (Component.MULTI_TIMEFRAME_ALIGNMENT, 0.13, 0.06, False),
            (Component.DERIVATIVES_CONTEXT, 0.0, 0.02, False),
        )
    else:
        values = (
            (Component.DIRECTIONAL_STRUCTURE, 0.20, 0.12, True),
            (Component.TREND_QUALITY, 0.24, 0.16, True),
            (Component.MOMENTUM, 0.12, 0.08, True),
            (Component.RELATIVE_STRENGTH, 0.16, 0.15, False),
            (Component.PARTICIPATION, 0.08, 0.08, False),
            (Component.STRUCTURAL_READINESS, 0.07, 0.10, False),
            (Component.VOLATILITY_SUITABILITY, 0.0, 0.10, False),
            (Component.REMAINING_ROOM, 0.0, 0.13, False),
            (Component.EXTENSION_CHASE_RISK, 0.0, 0.0, False),
            (Component.MULTI_TIMEFRAME_ALIGNMENT, 0.13, 0.06, False),
            (Component.DERIVATIVES_CONTEXT, 0.0, 0.02, False),
        )
    return tuple(
        ComponentWeight(
            component=component,
            direction_weight=direction,
            opportunity_weight=opportunity,
            required=required,
        )
        for component, direction, opportunity, required in values
    )


def _rules(style: TradeStyle) -> tuple[EvidenceRule, ...]:
    movement_scale_5 = 3.0 if style is TradeStyle.DAY else 6.0
    movement_scale_20 = 7.0 if style is TradeStyle.DAY else 15.0
    slope_scale = 1.0 if style is TradeStyle.DAY else 2.0
    relative_scale = 4.0 if style is TradeStyle.DAY else 8.0
    volatility = (0.2, 1.4, 4.0) if style is TradeStyle.DAY else (0.5, 2.5, 7.0)
    rules = (
        _rule(
            "structure.hh",
            Component.DIRECTIONAL_STRUCTURE,
            Source.PRIMARY,
            "structure.higher_high_fraction",
            Role.DIRECTIONAL,
            Transform.UNSIGNED_LINEAR,
            0.25,
            parameters=(("bars", 20),),
            required=True,
            floor=0.0,
            ceiling=1.0,
            positive_code=Code.POSITIVE_STRUCTURE,
        ),
        _rule(
            "structure.hl",
            Component.DIRECTIONAL_STRUCTURE,
            Source.PRIMARY,
            "structure.higher_low_fraction",
            Role.DIRECTIONAL,
            Transform.UNSIGNED_LINEAR,
            0.25,
            parameters=(("bars", 20),),
            required=True,
            floor=0.0,
            ceiling=1.0,
            positive_code=Code.POSITIVE_STRUCTURE,
        ),
        _rule(
            "structure.lh",
            Component.DIRECTIONAL_STRUCTURE,
            Source.PRIMARY,
            "structure.lower_high_fraction",
            Role.DIRECTIONAL,
            Transform.UNSIGNED_LINEAR,
            0.25,
            parameters=(("bars", 20),),
            required=True,
            orientation=-1,
            floor=0.0,
            ceiling=1.0,
            negative_code=Code.NEGATIVE_STRUCTURE,
        ),
        _rule(
            "structure.ll",
            Component.DIRECTIONAL_STRUCTURE,
            Source.PRIMARY,
            "structure.lower_low_fraction",
            Role.DIRECTIONAL,
            Transform.UNSIGNED_LINEAR,
            0.25,
            parameters=(("bars", 20),),
            required=True,
            orientation=-1,
            floor=0.0,
            ceiling=1.0,
            negative_code=Code.NEGATIVE_STRUCTURE,
        ),
        _rule(
            "trend.efficiency",
            Component.TREND_QUALITY,
            Source.PRIMARY,
            "trend.signed_efficiency",
            Role.DIRECTIONAL,
            Transform.SIGNED_LINEAR,
            0.30,
            parameters=(("bars", 20),),
            required=True,
            scale=0.7,
            positive_code=Code.POSITIVE_SLOPE,
            negative_code=Code.NEGATIVE_SLOPE,
        ),
        _rule(
            "trend.slope",
            Component.TREND_QUALITY,
            Source.PRIMARY,
            "trend.linear_slope_percent",
            Role.DIRECTIONAL,
            Transform.SIGNED_LINEAR,
            0.30,
            parameters=(("bars", 20),),
            required=True,
            scale=slope_scale,
            positive_code=Code.POSITIVE_SLOPE,
            negative_code=Code.NEGATIVE_SLOPE,
        ),
        _rule(
            "trend.ema_spread",
            Component.TREND_QUALITY,
            Source.PRIMARY,
            "trend.ema_spread_percent",
            Role.DIRECTIONAL,
            Transform.SIGNED_LINEAR,
            0.25,
            parameters=(("fast_period", 20), ("slow_period", 50)),
            required=True,
            scale=5.0,
            positive_code=Code.ABOVE_EMA20,
            negative_code=Code.BELOW_EMA20,
        ),
        _rule(
            "indicator.rsi",
            Component.TREND_QUALITY,
            Source.INDICATOR,
            "rsi",
            Role.DIRECTIONAL,
            Transform.CENTERED_LINEAR,
            0.10,
            parameters=(("period", 14),),
            output_name="rsi",
            center=50.0,
            scale=25.0,
            positive_code=Code.POSITIVE_MOMENTUM,
            negative_code=Code.NEGATIVE_MOMENTUM,
        ),
        _rule(
            "indicator.adx",
            Component.TREND_QUALITY,
            Source.INDICATOR,
            "adx",
            Role.SUITABILITY,
            Transform.UNSIGNED_LINEAR,
            0.05,
            parameters=(("period", 14),),
            output_name="adx",
            floor=15.0,
            ceiling=35.0,
        ),
        _rule(
            "momentum.return_5",
            Component.MOMENTUM,
            Source.PRIMARY,
            "return.percent",
            Role.DIRECTIONAL,
            Transform.SIGNED_LINEAR,
            0.55,
            parameters=(("bars", 5),),
            required=True,
            scale=movement_scale_5,
            positive_code=Code.POSITIVE_MOMENTUM,
            negative_code=Code.NEGATIVE_MOMENTUM,
        ),
        _rule(
            "momentum.return_20",
            Component.MOMENTUM,
            Source.PRIMARY,
            "return.percent",
            Role.DIRECTIONAL,
            Transform.SIGNED_LINEAR,
            0.45,
            parameters=(("bars", 20),),
            required=True,
            scale=movement_scale_20,
            positive_code=Code.POSITIVE_MOMENTUM,
            negative_code=Code.NEGATIVE_MOMENTUM,
        ),
        _rule(
            "relative.spread",
            Component.RELATIVE_STRENGTH,
            Source.RELATIVE,
            "relative.return_spread_percent",
            Role.DIRECTIONAL,
            Transform.SIGNED_LINEAR,
            0.60,
            parameters=(("bars", 20),),
            scale=relative_scale,
            positive_code=Code.RELATIVE_OUTPERFORMANCE,
            negative_code=Code.RELATIVE_UNDERPERFORMANCE,
        ),
        _rule(
            "relative.consistency",
            Component.RELATIVE_STRENGTH,
            Source.RELATIVE,
            "relative.strength_consistency",
            Role.DIRECTIONAL,
            Transform.CENTERED_LINEAR,
            0.40,
            parameters=(("bars", 20),),
            center=0.5,
            scale=0.5,
            positive_code=Code.RELATIVE_OUTPERFORMANCE,
            negative_code=Code.RELATIVE_UNDERPERFORMANCE,
        ),
        _rule(
            "participation.balance",
            Component.PARTICIPATION,
            Source.PRIMARY,
            "participation.signed_volume_balance",
            Role.DIRECTIONAL,
            Transform.SIGNED_LINEAR,
            0.70,
            parameters=(("bars", 20),),
            scale=0.7,
            positive_code=Code.POSITIVE_PARTICIPATION,
            negative_code=Code.NEGATIVE_PARTICIPATION,
        ),
        _rule(
            "participation.relative_volume",
            Component.PARTICIPATION,
            Source.PRIMARY,
            "volume.relative",
            Role.SUITABILITY,
            Transform.UNSIGNED_LINEAR,
            0.30,
            parameters=(("bars", 20),),
            floor=0.5,
            ceiling=2.0,
        ),
        _rule(
            "readiness.position",
            Component.STRUCTURAL_READINESS,
            Source.PRIMARY,
            "structure.position_vs_prior_range",
            Role.DIRECTIONAL,
            Transform.CENTERED_LINEAR,
            0.35,
            parameters=(("bars", 20),),
            center=50.0,
            scale=50.0,
            positive_code=Code.NEAR_PRIOR_HIGH,
            negative_code=Code.NEAR_PRIOR_LOW,
        ),
        _rule(
            "readiness.compression",
            Component.STRUCTURAL_READINESS,
            Source.PRIMARY,
            "structure.range_compression_ratio",
            Role.SUITABILITY,
            Transform.LOWER_BETTER,
            0.25,
            parameters=(("long_bars", 20), ("short_bars", 10)),
            floor=0.5,
            ceiling=1.2,
            positive_code=Code.RANGE_COMPRESSED,
        ),
        _rule(
            "readiness.breakout",
            Component.STRUCTURAL_READINESS,
            Source.PRIMARY,
            "breakout.above_prior_high_percent",
            Role.DIRECTIONAL,
            Transform.UNSIGNED_LINEAR,
            0.20,
            parameters=(("bars", 20),),
            floor=0.0,
            ceiling=2.0,
            positive_code=Code.BREAKOUT_EXCURSION,
        ),
        _rule(
            "readiness.breakdown",
            Component.STRUCTURAL_READINESS,
            Source.PRIMARY,
            "breakdown.below_prior_low_percent",
            Role.DIRECTIONAL,
            Transform.UNSIGNED_LINEAR,
            0.20,
            parameters=(("bars", 20),),
            orientation=-1,
            floor=0.0,
            ceiling=2.0,
            negative_code=Code.BREAKDOWN_EXCURSION,
        ),
        _rule(
            "volatility.atr",
            Component.VOLATILITY_SUITABILITY,
            Source.PRIMARY,
            "volatility.atr_percent",
            Role.SUITABILITY,
            Transform.TRIANGLE,
            1.0,
            parameters=(("period", 14),),
            floor=volatility[0],
            target=volatility[1],
            ceiling=volatility[2],
            positive_code=Code.VOLATILITY_USABLE,
        ),
        _rule(
            "room.positive",
            Component.REMAINING_ROOM,
            Source.PRIMARY,
            "resistance.distance_atr",
            Role.SUITABILITY,
            Transform.POSITIVE_ROOM,
            0.5,
            parameters=(("atr_period", 14), ("bars", 20)),
            scale=3.0,
            ceiling=1.5,
            post_boundary_credit=0.0,
            positive_code=Code.POSITIVE_ROOM_AVAILABLE,
        ),
        _rule(
            "room.negative",
            Component.REMAINING_ROOM,
            Source.PRIMARY,
            "support.distance_atr",
            Role.SUITABILITY,
            Transform.NEGATIVE_ROOM,
            0.5,
            parameters=(("atr_period", 14), ("bars", 20)),
            scale=3.0,
            ceiling=1.5,
            post_boundary_credit=0.0,
            positive_code=Code.NEGATIVE_ROOM_AVAILABLE,
        ),
        _rule(
            "extension.ema",
            Component.EXTENSION_CHASE_RISK,
            Source.PRIMARY,
            "trend.distance_from_ema_atr",
            Role.PENALTY,
            Transform.SIGNED_LINEAR,
            0.45,
            parameters=(("atr_period", 14), ("ma_period", 20)),
            scale=3.0,
            code_threshold=0.65,
            positive_code=Code.HIGH_EXTENSION,
            negative_code=Code.HIGH_EXTENSION,
        ),
        _rule(
            "extension.return",
            Component.EXTENSION_CHASE_RISK,
            Source.PRIMARY,
            "return.percent",
            Role.PENALTY,
            Transform.SIGNED_LINEAR,
            0.35,
            parameters=(("bars", 20),),
            scale=movement_scale_20,
            code_threshold=0.65,
            positive_code=Code.HIGH_EXTENSION,
            negative_code=Code.HIGH_EXTENSION,
        ),
        _rule(
            "extension.range",
            Component.EXTENSION_CHASE_RISK,
            Source.PRIMARY,
            "structure.latest_bar_range_vs_average",
            Role.PENALTY,
            Transform.UNSIGNED_LINEAR,
            0.20,
            parameters=(("bars", 20),),
            floor=1.0,
            ceiling=3.0,
            code_threshold=0.65,
            positive_code=Code.HIGH_EXTENSION,
        ),
        _rule(
            "mtf.positive",
            Component.MULTI_TIMEFRAME_ALIGNMENT,
            Source.MULTI_TIMEFRAME,
            "mtf.positive_return_fraction",
            Role.DIRECTIONAL,
            Transform.UNSIGNED_LINEAR,
            0.35,
            parameters=(("bars", 20),),
            floor=0.0,
            ceiling=1.0,
            positive_code=Code.MTF_POSITIVE_EVIDENCE,
        ),
        _rule(
            "mtf.negative",
            Component.MULTI_TIMEFRAME_ALIGNMENT,
            Source.MULTI_TIMEFRAME,
            "mtf.negative_return_fraction",
            Role.DIRECTIONAL,
            Transform.UNSIGNED_LINEAR,
            0.35,
            parameters=(("bars", 20),),
            orientation=-1,
            floor=0.0,
            ceiling=1.0,
            negative_code=Code.MTF_NEGATIVE_EVIDENCE,
        ),
        _rule(
            "mtf.agreement",
            Component.MULTI_TIMEFRAME_ALIGNMENT,
            Source.MULTI_TIMEFRAME,
            "mtf.directional_agreement_fraction",
            Role.SUITABILITY,
            Transform.UNSIGNED_LINEAR,
            0.20,
            parameters=(("bars", 20),),
            floor=0.33,
            ceiling=1.0,
            positive_code=Code.MTF_AGREEMENT_EVIDENCE,
        ),
        _rule(
            "mtf.disagreement",
            Component.MULTI_TIMEFRAME_ALIGNMENT,
            Source.MULTI_TIMEFRAME,
            "mtf.disagreement_fraction",
            Role.PENALTY,
            Transform.UNSIGNED_LINEAR,
            0.10,
            parameters=(("bars", 20),),
            floor=0.0,
            ceiling=0.67,
            code_threshold=0.5,
            positive_code=Code.MTF_DISAGREEMENT_EVIDENCE,
        ),
        _rule(
            "derivatives.ce_spread",
            Component.DERIVATIVES_CONTEXT,
            Source.DERIVATIVES,
            "derivatives.atm_ce_bid_ask_spread_percent",
            Role.SUITABILITY,
            Transform.LOWER_BETTER,
            0.5,
            floor=0.5,
            ceiling=8.0,
            positive_code=Code.DERIVATIVES_LIQUIDITY_USABLE,
        ),
        _rule(
            "derivatives.pe_spread",
            Component.DERIVATIVES_CONTEXT,
            Source.DERIVATIVES,
            "derivatives.atm_pe_bid_ask_spread_percent",
            Role.SUITABILITY,
            Transform.LOWER_BETTER,
            0.5,
            floor=0.5,
            ceiling=8.0,
            positive_code=Code.DERIVATIVES_LIQUIDITY_USABLE,
        ),
    )
    return rules


def default_policy(trade_style: TradeStyle, *, policy_version: str = "1.0") -> BaselinePolicy:
    """Return the transparent, generic engineering baseline for one cadence."""
    if policy_version != "1.0":
        raise BaselinePolicyError(f"unsupported baseline policy version: {policy_version}")
    return BaselinePolicy(
        policy_id=f"tiaf-a2.9-{trade_style.value.casefold()}",
        policy_version=policy_version,
        trade_style=trade_style,
        component_weights=_component_weights(trade_style),
        evidence_rules=_rules(trade_style),
        direction_thresholds=DirectionThresholds(
            minimum_score=52.0,
            minimum_margin=8.0,
            conflict_score=42.0,
            component_conflict_score=35.0,
        ),
        classification_thresholds=ClassificationThresholds(
            minimum_alignment=52.0,
            minimum_opportunity_score=35.0,
            early_opportunity_score=50.0,
            top_mover_momentum=70.0,
            top_mover_participation=52.0,
            mature_extension=65.0,
            mature_room=20.0,
        ),
        penalties=PenaltyPolicy(
            extension_points=25.0,
            conflict_points=15.0,
            partial_quality_points=5.0,
            degraded_quality_points=15.0,
            unavailable_quality_points=100.0,
            aging_freshness_points=4.0,
            unknown_freshness_points=8.0,
        ),
        quality_factors=(
            QualityFactor(quality=DataQuality.GOOD, factor=1.0),
            QualityFactor(quality=DataQuality.PARTIAL, factor=0.8),
            QualityFactor(quality=DataQuality.DEGRADED, factor=0.55),
            QualityFactor(quality=DataQuality.UNAVAILABLE, factor=0.0),
        ),
        critical_freshness_sources=(Source.PRIMARY,),
        rounding_digits=6,
        metadata={
            "status": "generic_engineering_baseline_not_fitted",
            "calibration": "future_A2.10_A7_evaluation",
            "completed_bar_only": True,
        },
    )
