"""Closed vocabularies for the bounded A4 evidence-enrichment application bridge."""

from enum import StrEnum


class EvidenceNeedAdmissionOutcome(StrEnum):
    ADMITTED = "ADMITTED"
    DENIED_AUTHORITY = "DENIED_AUTHORITY"
    DENIED_BUDGET = "DENIED_BUDGET"
    DENIED_POLICY = "DENIED_POLICY"
    DUPLICATE = "DUPLICATE"
    UNSUPPORTED_CAPABILITY = "UNSUPPORTED_CAPABILITY"
    NOT_MATERIAL = "NOT_MATERIAL"
    DEADLINE_EXCEEDED = "DEADLINE_EXCEEDED"
    ALREADY_RESOLVED = "ALREADY_RESOLVED"


class WorkflowAdapter(StrEnum):
    SERIAL = "SERIAL"
    LANGGRAPH = "LANGGRAPH"


class EvidenceCaptureStatus(StrEnum):
    NEW_INFORMATION = "NEW_INFORMATION"
    PARTIAL = "PARTIAL"
    NO_NEW_INFORMATION = "NO_NEW_INFORMATION"
    FAILED = "FAILED"


class EvidenceChangeKind(StrEnum):
    SAFE_CONTEXT = "SAFE_CONTEXT"
    SOURCE_AUTHORITY = "SOURCE_AUTHORITY"
    CONFIRMATION = "CONFIRMATION"
    FACTUAL_CONFLICT = "FACTUAL_CONFLICT"
    PRICE_OR_MARKET_STATE = "PRICE_OR_MARKET_STATE"
    SPECIALIST_INPUT = "SPECIALIST_INPUT"
    EQUIVALENT = "EQUIVALENT"
    IRRELEVANT = "IRRELEVANT"


class EnrichmentStopReason(StrEnum):
    RESOLVED = "RESOLVED"
    NO_NEW_INFORMATION = "NO_NEW_INFORMATION"
    ROUND_LIMIT = "ROUND_LIMIT"
    ADMISSION_DENIED = "ADMISSION_DENIED"
    ACQUISITION_FAILED = "ACQUISITION_FAILED"
    UPSTREAM_REFRESH_REQUIRED = "UPSTREAM_REFRESH_REQUIRED"
    SUCCESSOR_FAILED = "SUCCESSOR_FAILED"
    REEVALUATION_FAILED = "REEVALUATION_FAILED"


class FindingLineageState(StrEnum):
    PRESERVED = "PRESERVED"
    RECOMPUTED = "RECOMPUTED"
    RESOLVED = "RESOLVED"
    NEW = "NEW"
