"""Narrow same-process capability facade; no transport, provider or A4 runtime."""

from .capabilities import capability_catalog
from .contracts import (
    A4InputProjectRequest,
    A4InputProjectResult,
    BaselineAssessRequest,
    BaselineAssessResult,
    CallerGrant,
    CapabilityDescriptor,
    CapabilityListRequest,
    CapabilityListResult,
    EffectiveAdmission,
    FacadeErrorRecord,
    FacadeOperationRequest,
    InvocationBudget,
    InvocationMetadata,
    InvocationScope,
    InvocationUsage,
    OperatorPolicy,
    OpportunityAssembleRequest,
    OpportunityAssembleResult,
    RecordedReplayRequest,
    RecordedReplayResult,
    ReplayVerifyRequest,
    ReplayVerifyResult,
    TrustedArtifact,
    TrustedFacadeConfig,
)
from .enums import (
    ArtifactKind,
    CapabilityAvailability,
    CostKnowledge,
    EffectClass,
    FacadeAuthorityScope,
    FacadeStatus,
    InterfaceLevel,
    LifecycleState,
    ReplayResultKind,
    ReplaySupport,
)
from .errors import FacadeInvocationError
from .runtime import LocalFacadeClient, LocalFacadeOwner, create_local_facade

__all__ = [
    "A4InputProjectRequest",
    "A4InputProjectResult",
    "ArtifactKind",
    "BaselineAssessRequest",
    "BaselineAssessResult",
    "CallerGrant",
    "CapabilityAvailability",
    "CapabilityDescriptor",
    "CapabilityListRequest",
    "CapabilityListResult",
    "CostKnowledge",
    "EffectClass",
    "EffectiveAdmission",
    "FacadeAuthorityScope",
    "FacadeErrorRecord",
    "FacadeInvocationError",
    "FacadeOperationRequest",
    "FacadeStatus",
    "InterfaceLevel",
    "InvocationBudget",
    "InvocationMetadata",
    "InvocationScope",
    "InvocationUsage",
    "LifecycleState",
    "LocalFacadeClient",
    "LocalFacadeOwner",
    "OperatorPolicy",
    "OpportunityAssembleRequest",
    "OpportunityAssembleResult",
    "RecordedReplayRequest",
    "RecordedReplayResult",
    "ReplayResultKind",
    "ReplaySupport",
    "ReplayVerifyRequest",
    "ReplayVerifyResult",
    "TrustedArtifact",
    "TrustedFacadeConfig",
    "capability_catalog",
    "create_local_facade",
]
