"""Closed vocabularies for the trusted same-process facade."""

from enum import StrEnum


class InterfaceLevel(StrEnum):
    PUBLIC = "PUBLIC"
    ENGINEERING = "ENGINEERING"


class EffectClass(StrEnum):
    PURE = "PURE"
    CAPTURED_READ = "CAPTURED_READ"
    LIVE_READ = "LIVE_READ"
    PERSIST = "PERSIST"


class CapabilityAvailability(StrEnum):
    AVAILABLE = "AVAILABLE"
    UNAVAILABLE = "UNAVAILABLE"
    DEPRECATED = "DEPRECATED"


class CapabilitySemanticRole(StrEnum):
    BASELINE = "BASELINE"
    CAPABILITY_DISCOVERY = "CAPABILITY_DISCOVERY"
    OPPORTUNITY_INTELLIGENCE = "OPPORTUNITY_INTELLIGENCE"
    CHALLENGE_ARBITRATION = "CHALLENGE_ARBITRATION"
    POSITION_INTELLIGENCE = "POSITION_INTELLIGENCE"
    REPLAY = "REPLAY"
    ENGINEERING = "ENGINEERING"


class PluggabilityLevel(StrEnum):
    STRUCTURAL = "STRUCTURAL"
    COLD = "COLD"
    HOT = "HOT"


class CapabilityDependencyKind(StrEnum):
    INPUT_CONTRACT = "INPUT_CONTRACT"
    CAPABILITY = "CAPABILITY"


class CapabilityEntitlement(StrEnum):
    CAPTURED_EVIDENCE = "CAPTURED_EVIDENCE"
    POSITION_DATA = "POSITION_DATA"
    ENGINEERING = "ENGINEERING"


class CapabilityRegistrationState(StrEnum):
    REGISTERED = "REGISTERED"


class CapabilityDiscoveryState(StrEnum):
    REGISTERED = "REGISTERED"
    DISCOVERABLE = "DISCOVERABLE"
    DISABLED = "DISABLED"
    UNAUTHORIZED = "UNAUTHORIZED"
    DEPENDENCY_UNAVAILABLE = "DEPENDENCY_UNAVAILABLE"
    UNSUPPORTED = "UNSUPPORTED"
    UNKNOWN = "UNKNOWN"


class CapabilityReadinessState(StrEnum):
    REQUIRES_RUNTIME_CHECK = "REQUIRES_RUNTIME_CHECK"
    DISABLED = "DISABLED"
    UNAUTHORIZED = "UNAUTHORIZED"
    DEPENDENCY_UNAVAILABLE = "DEPENDENCY_UNAVAILABLE"
    UNSUPPORTED = "UNSUPPORTED"
    UNKNOWN = "UNKNOWN"


class MonitoringCompatibility(StrEnum):
    NOT_MONITORABLE = "NOT_MONITORABLE"
    SEMANTICALLY_REPEATABLE = "SEMANTICALLY_REPEATABLE"
    MONITORING_FUTURE = "MONITORING_FUTURE"


class ReplaySupport(StrEnum):
    NONE = "NONE"
    RECORDED = "RECORDED"
    DETERMINISTIC = "DETERMINISTIC"


class CostKnowledge(StrEnum):
    KNOWN_ZERO = "KNOWN_ZERO"
    UNPRICED = "UNPRICED"
    UNKNOWN = "UNKNOWN"


class FacadeStatus(StrEnum):
    COMPLETED = "COMPLETED"
    INVALID_REQUEST = "INVALID_REQUEST"
    UNSUPPORTED = "UNSUPPORTED"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    BUDGET_EXCEEDED = "BUDGET_EXCEEDED"
    MODEL_DISABLED = "MODEL_DISABLED"
    UNAVAILABLE = "UNAVAILABLE"
    FAILED = "FAILED"
    REPLAY_INTEGRITY_ERROR = "REPLAY_INTEGRITY_ERROR"
    PARTIAL = "PARTIAL"
    STALE = "STALE"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"


class FacadeAuthorityScope(StrEnum):
    DISCOVER_CAPABILITIES = "DISCOVER_CAPABILITIES"
    ASSESS_BASELINE = "ASSESS_BASELINE"
    ASSEMBLE_OPPORTUNITY = "ASSEMBLE_OPPORTUNITY"
    PROJECT_A4_INPUT = "PROJECT_A4_INPUT"
    EVALUATE_A4 = "EVALUATE_A4"
    ASSESS_POSITION = "ASSESS_POSITION"
    READ_REPLAY = "READ_REPLAY"
    VERIFY_REPLAY = "VERIFY_REPLAY"


class ArtifactKind(StrEnum):
    A38_CAPTURE = "A38_CAPTURE"
    A3_PACKAGE = "A3_PACKAGE"
    FOUNDATION_BUILD_INPUT = "FOUNDATION_BUILD_INPUT"
    FOUNDATION_CAPTURE = "FOUNDATION_CAPTURE"
    A5_POSITION_REQUEST = "A5_POSITION_REQUEST"
    A5_CAPTURE = "A5_CAPTURE"


class LifecycleState(StrEnum):
    CONFIGURING = "CONFIGURING"
    STARTED = "STARTED"
    SHUTDOWN = "SHUTDOWN"


class ReplayResultKind(StrEnum):
    A3_RECORDED = "A3_RECORDED"
    FOUNDATION_RECORDED = "FOUNDATION_RECORDED"
    A5_RECORDED = "A5_RECORDED"
