"""Closed vocabularies for the trusted same-process facade."""

from enum import StrEnum


class InterfaceLevel(StrEnum):
    PUBLIC = "PUBLIC"
    ENGINEERING = "ENGINEERING"


class EffectClass(StrEnum):
    PURE = "PURE"
    CAPTURED_READ = "CAPTURED_READ"
    LIVE_READ = "LIVE_READ"
    PERSIST = "PERSIST"


class CapabilityAvailability(StrEnum):
    AVAILABLE = "AVAILABLE"
    UNAVAILABLE = "UNAVAILABLE"
    DEPRECATED = "DEPRECATED"


class ReplaySupport(StrEnum):
    NONE = "NONE"
    RECORDED = "RECORDED"
    DETERMINISTIC = "DETERMINISTIC"


class CostKnowledge(StrEnum):
    KNOWN_ZERO = "KNOWN_ZERO"
    UNPRICED = "UNPRICED"
    UNKNOWN = "UNKNOWN"


class FacadeStatus(StrEnum):
    COMPLETED = "COMPLETED"
    INVALID_REQUEST = "INVALID_REQUEST"
    UNSUPPORTED = "UNSUPPORTED"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    BUDGET_EXCEEDED = "BUDGET_EXCEEDED"
    MODEL_DISABLED = "MODEL_DISABLED"
    UNAVAILABLE = "UNAVAILABLE"
    FAILED = "FAILED"
    REPLAY_INTEGRITY_ERROR = "REPLAY_INTEGRITY_ERROR"
    PARTIAL = "PARTIAL"
    STALE = "STALE"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"


class FacadeAuthorityScope(StrEnum):
    DISCOVER_CAPABILITIES = "DISCOVER_CAPABILITIES"
    ASSESS_BASELINE = "ASSESS_BASELINE"
    ASSEMBLE_OPPORTUNITY = "ASSEMBLE_OPPORTUNITY"
    PROJECT_A4_INPUT = "PROJECT_A4_INPUT"
    EVALUATE_A4 = "EVALUATE_A4"
    READ_REPLAY = "READ_REPLAY"
    VERIFY_REPLAY = "VERIFY_REPLAY"


class ArtifactKind(StrEnum):
    A38_CAPTURE = "A38_CAPTURE"
    A3_PACKAGE = "A3_PACKAGE"
    FOUNDATION_BUILD_INPUT = "FOUNDATION_BUILD_INPUT"
    FOUNDATION_CAPTURE = "FOUNDATION_CAPTURE"


class LifecycleState(StrEnum):
    CONFIGURING = "CONFIGURING"
    STARTED = "STARTED"
    SHUTDOWN = "SHUTDOWN"


class ReplayResultKind(StrEnum):
    A3_RECORDED = "A3_RECORDED"
    FOUNDATION_RECORDED = "FOUNDATION_RECORDED"
