"""Stable A3.6 relative-context interpretation states."""

from enum import StrEnum


class RelativeStrengthState(StrEnum):
    STRONGLY_OUTPERFORMING = "STRONGLY_OUTPERFORMING"
    OUTPERFORMING = "OUTPERFORMING"
    MILDLY_OUTPERFORMING = "MILDLY_OUTPERFORMING"
    INLINE = "INLINE"
    MILDLY_UNDERPERFORMING = "MILDLY_UNDERPERFORMING"
    UNDERPERFORMING = "UNDERPERFORMING"
    STRONGLY_UNDERPERFORMING = "STRONGLY_UNDERPERFORMING"
    MIXED = "MIXED"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"


class RelativeConsistencyState(StrEnum):
    CONSISTENT = "CONSISTENT"
    VARIABLE = "VARIABLE"
    CONSISTENTLY_WEAK = "CONSISTENTLY_WEAK"
    UNKNOWN = "UNKNOWN"


class RelativeMtfState(StrEnum):
    ALIGNED_POSITIVE = "ALIGNED_POSITIVE"
    ALIGNED_NEGATIVE = "ALIGNED_NEGATIVE"
    CONFLICT = "CONFLICT"
    SINGLE_TIMEFRAME = "SINGLE_TIMEFRAME"
    UNKNOWN = "UNKNOWN"


class RelativeLeadershipState(StrEnum):
    LEADER = "LEADER"
    ABOVE_AVERAGE = "ABOVE_AVERAGE"
    INLINE = "INLINE"
    LAGGARD = "LAGGARD"
    SEVERE_LAGGARD = "SEVERE_LAGGARD"
    UNKNOWN = "UNKNOWN"


class RelativeExtremeState(StrEnum):
    EXTENDED_LEADERSHIP = "EXTENDED_LEADERSHIP"
    EXTENDED_WEAKNESS = "EXTENDED_WEAKNESS"
    NOT_EXTREME = "NOT_EXTREME"
    UNKNOWN = "UNKNOWN"


class RelativeReasonCode(StrEnum):
    RELATIVE_OUTPERFORMANCE = "RELATIVE_OUTPERFORMANCE"
    RELATIVE_UNDERPERFORMANCE = "RELATIVE_UNDERPERFORMANCE"
    RELATIVE_LEADERSHIP = "RELATIVE_LEADERSHIP"
    RELATIVE_LAG = "RELATIVE_LAG"
    RELATIVE_INLINE = "RELATIVE_INLINE"
    RELATIVE_MTF_ALIGNED = "RELATIVE_MTF_ALIGNED"
    RELATIVE_MTF_CONFLICT = "RELATIVE_MTF_CONFLICT"
    RELATIVE_EXTENDED = "RELATIVE_EXTENDED"
    BENCHMARK_MAPPING_MISSING = "BENCHMARK_MAPPING_MISSING"
    BENCHMARK_MISMATCH = "BENCHMARK_MISMATCH"
    RELATIVE_EVIDENCE_PARTIAL = "RELATIVE_EVIDENCE_PARTIAL"
    RELATIVE_EVIDENCE_STALE = "RELATIVE_EVIDENCE_STALE"
    RELATIVE_EVIDENCE_INSUFFICIENT = "RELATIVE_EVIDENCE_INSUFFICIENT"
