"""Public deterministic A5.1 position-intelligence surface."""

from .contracts import (
    A5Capture,
    A5DeterministicPolicy,
    A5PolicyComparison,
    A5ReplayResult,
    A5RunRecord,
    A5Usage,
    A5VerificationResult,
    MonitoringNeed,
    PositionIntelligenceRequest,
    PositionIntelligenceResult,
    PositionSignal,
    PositionSnapshot,
    ProtectionIntent,
    ReferenceLevel,
    WatchMandate,
)
from .enums import (
    A5ExecutionStatus,
    A5FailureCode,
    A5ReplayMode,
    MonitoringLifecycle,
    MonitoringPriority,
    MonitoringTriggerKind,
    OperationalPositionState,
    PositionFreshness,
    PositionProduct,
    PositionRecommendation,
    PositionRiskPosture,
    PositionShape,
    PositionSide,
    PositionSignalKind,
    ProtectionIntentKind,
    ReferenceLevelKind,
    RemainingOpportunity,
    ThesisHealth,
)
from .errors import (
    A5EvaluationError,
    A5InputIntegrityError,
    A5OutputIntegrityError,
    A5ReplayIntegrityError,
    UnsupportedA5PolicyError,
)
from .evaluation import (
    evaluate_position,
    result_semantic_payload,
    validate_request,
    validate_result,
    validate_run,
)
from .freshness import evaluate_freshness
from .monitoring import build_monitoring_needs, build_watch_mandate
from .policy import deterministic_policy, require_supported_policy
from .replay import (
    capture_json,
    capture_run,
    compare_policy,
    replay_recorded,
    validate_capture,
    verify_deterministic,
)

__all__ = [
    "A5Capture",
    "A5DeterministicPolicy",
    "A5EvaluationError",
    "A5ExecutionStatus",
    "A5FailureCode",
    "A5InputIntegrityError",
    "A5OutputIntegrityError",
    "A5PolicyComparison",
    "A5ReplayIntegrityError",
    "A5ReplayMode",
    "A5ReplayResult",
    "A5RunRecord",
    "A5Usage",
    "A5VerificationResult",
    "MonitoringLifecycle",
    "MonitoringNeed",
    "MonitoringPriority",
    "MonitoringTriggerKind",
    "OperationalPositionState",
    "PositionFreshness",
    "PositionIntelligenceRequest",
    "PositionIntelligenceResult",
    "PositionProduct",
    "PositionRecommendation",
    "PositionRiskPosture",
    "PositionShape",
    "PositionSide",
    "PositionSignal",
    "PositionSignalKind",
    "PositionSnapshot",
    "ProtectionIntent",
    "ProtectionIntentKind",
    "ReferenceLevel",
    "ReferenceLevelKind",
    "RemainingOpportunity",
    "ThesisHealth",
    "UnsupportedA5PolicyError",
    "WatchMandate",
    "build_monitoring_needs",
    "build_watch_mandate",
    "capture_json",
    "capture_run",
    "compare_policy",
    "deterministic_policy",
    "evaluate_freshness",
    "evaluate_position",
    "replay_recorded",
    "require_supported_policy",
    "result_semantic_payload",
    "validate_capture",
    "validate_request",
    "validate_result",
    "validate_run",
    "verify_deterministic",
]
