"""Closed vocabularies for deterministic A5.1 position intelligence."""

from enum import StrEnum


class PositionSide(StrEnum):
    LONG = "LONG"
    SHORT = "SHORT"


class PositionShape(StrEnum):
    SINGLE_LEG = "SINGLE_LEG"
    MULTI_LEG = "MULTI_LEG"


class PositionProduct(StrEnum):
    DELIVERY = "DELIVERY"
    INTRADAY = "INTRADAY"
    MARGIN = "MARGIN"
    UNKNOWN = "UNKNOWN"


class OperationalPositionState(StrEnum):
    OPEN = "OPEN"
    CLOSING = "CLOSING"
    CLOSED = "CLOSED"
    UNKNOWN = "UNKNOWN"


class PositionFreshness(StrEnum):
    CURRENT = "CURRENT"
    STALE = "STALE"
    UNKNOWN = "UNKNOWN"
    INVALID = "INVALID"


class PositionRiskPosture(StrEnum):
    CAPITAL_AT_RISK = "CAPITAL_AT_RISK"
    RISK_REDUCED = "RISK_REDUCED"
    PROFIT_PROTECTION_ACTIVE = "PROFIT_PROTECTION_ACTIVE"
    UNDETERMINED = "UNDETERMINED"


class ThesisHealth(StrEnum):
    INTACT = "INTACT"
    STRENGTHENED = "STRENGTHENED"
    WEAKENED = "WEAKENED"
    INVALIDATED = "INVALIDATED"
    UNDETERMINED = "UNDETERMINED"


class PositionRecommendation(StrEnum):
    MAINTAIN = "MAINTAIN"
    WATCH_CLOSELY = "WATCH_CLOSELY"
    PROTECT = "PROTECT"
    REDUCE_RISK = "REDUCE_RISK"
    TRAIL_PROTECTION = "TRAIL_PROTECTION"
    EXIT_RECOMMENDED = "EXIT_RECOMMENDED"
    WAIT_FOR_CONFIRMATION = "WAIT_FOR_CONFIRMATION"
    ABSTAIN = "ABSTAIN"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"


class ProtectionIntentKind(StrEnum):
    HOLD_CURRENT_PROTECTION = "HOLD_CURRENT_PROTECTION"
    TIGHTEN_PROTECTION = "TIGHTEN_PROTECTION"
    LOCK_PROFIT = "LOCK_PROFIT"
    TRAIL_STRUCTURALLY = "TRAIL_STRUCTURALLY"
    EXIT_IF_INVALIDATED = "EXIT_IF_INVALIDATED"
    EXPRESSION_REFRESH_REQUIRED = "EXPRESSION_REFRESH_REQUIRED"
    NO_PROTECTION_CHANGE = "NO_PROTECTION_CHANGE"
    UNDETERMINED = "UNDETERMINED"


class RemainingOpportunity(StrEnum):
    STRONG = "STRONG"
    MODERATE = "MODERATE"
    LIMITED = "LIMITED"
    EXHAUSTED = "EXHAUSTED"
    UNKNOWN = "UNKNOWN"


class PositionSignalKind(StrEnum):
    STRUCTURAL_MILESTONE = "STRUCTURAL_MILESTONE"
    PROTECTION_CONFIRMED = "PROTECTION_CONFIRMED"
    FAVORABLE_CONTINUATION = "FAVORABLE_CONTINUATION"
    THESIS_WEAKENING = "THESIS_WEAKENING"
    THESIS_INVALIDATION = "THESIS_INVALIDATION"
    MATERIAL_CONFLICT = "MATERIAL_CONFLICT"
    LIQUIDITY_RISK = "LIQUIDITY_RISK"
    VOLATILITY_RISK = "VOLATILITY_RISK"
    EXPRESSION_UNSUITABLE = "EXPRESSION_UNSUITABLE"
    REMAINING_ROOM_STRONG = "REMAINING_ROOM_STRONG"
    REMAINING_ROOM_MODERATE = "REMAINING_ROOM_MODERATE"
    REMAINING_ROOM_LIMITED = "REMAINING_ROOM_LIMITED"
    REMAINING_ROOM_EXHAUSTED = "REMAINING_ROOM_EXHAUSTED"


class ReferenceLevelKind(StrEnum):
    STRUCTURAL_INVALIDATION = "STRUCTURAL_INVALIDATION"
    SUPPORT = "SUPPORT"
    RESISTANCE = "RESISTANCE"
    MILESTONE = "MILESTONE"
    SUPPLIED_STOP = "SUPPLIED_STOP"
    SUPPLIED_TARGET = "SUPPLIED_TARGET"


class MonitoringLifecycle(StrEnum):
    ACTIVE_POSITION = "ACTIVE_POSITION"
    INACTIVE = "INACTIVE"


class MonitoringPriority(StrEnum):
    ROUTINE = "ROUTINE"
    ELEVATED = "ELEVATED"
    URGENT = "URGENT"


class MonitoringTriggerKind(StrEnum):
    POSITION_SNAPSHOT_CHANGE = "POSITION_SNAPSHOT_CHANGE"
    PRICE_STRUCTURE = "PRICE_STRUCTURE"
    THESIS_INVALIDATION = "THESIS_INVALIDATION"
    CORPORATE_EVENT = "CORPORATE_EVENT"
    VOLATILITY_DERIVATIVES = "VOLATILITY_DERIVATIVES"
    EXPIRY_TIME = "EXPIRY_TIME"
    PERIODIC_HINT = "PERIODIC_HINT"
    MANUAL = "MANUAL"


class A5ExecutionStatus(StrEnum):
    COMPLETE = "COMPLETE"
    PARTIAL = "PARTIAL"
    UNSUPPORTED = "UNSUPPORTED"


class A5FailureCode(StrEnum):
    STALE_SNAPSHOT = "STALE_SNAPSHOT"
    UNKNOWN_FRESHNESS = "UNKNOWN_FRESHNESS"
    INVALID_SNAPSHOT = "INVALID_SNAPSHOT"
    INVALID_IDENTITY = "INVALID_IDENTITY"
    MISSING_A4_RESULT = "MISSING_A4_RESULT"
    UNSUPPORTED_SHAPE = "UNSUPPORTED_SHAPE"
    EXPIRED_INSTRUMENT = "EXPIRED_INSTRUMENT"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    CLOSED_OR_UNKNOWN_POSITION = "CLOSED_OR_UNKNOWN_POSITION"
    CORRUPT_REPLAY_ARTIFACT = "CORRUPT_REPLAY_ARTIFACT"
    POLICY_MISMATCH = "POLICY_MISMATCH"
    UNSUPPORTED_VERSION = "UNSUPPORTED_VERSION"


class A5ReplayMode(StrEnum):
    RECORDED = "RECORDED"
    DETERMINISTIC_VERIFICATION = "DETERMINISTIC_VERIFICATION"
    POLICY_COMPARISON = "POLICY_COMPARISON"
