"""Closed semantic vocabularies for the pre-A4 source foundation."""

from enum import StrEnum


class IdentityKnowledge(StrEnum):
    KNOWN = "KNOWN"
    UNKNOWN = "UNKNOWN"


class SourceEntityRole(StrEnum):
    PUBLISHER = "PUBLISHER"
    ISSUER = "ISSUER"
    SPEAKER = "SPEAKER"
    DISTRIBUTOR = "DISTRIBUTOR"
    UNKNOWN = "UNKNOWN"


class AuthorityApplicability(StrEnum):
    APPLICABLE = "APPLICABLE"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    UNKNOWN = "UNKNOWN"


class MeasureRole(StrEnum):
    ACTUAL = "ACTUAL"
    ESTIMATE = "ESTIMATE"
    GUIDANCE = "GUIDANCE"
    FORECAST = "FORECAST"
    UNKNOWN = "UNKNOWN"


class MeasureType(StrEnum):
    TEXT = "TEXT"
    BOOLEAN = "BOOLEAN"
    INTEGER = "INTEGER"
    NUMBER = "NUMBER"
    DATE = "DATE"
    DIRECTION = "DIRECTION"
    UNKNOWN = "UNKNOWN"


class AssertionValueKind(StrEnum):
    SCALAR = "SCALAR"
    INTERVAL = "INTERVAL"
    DIRECTION = "DIRECTION"
    MISSING = "MISSING"


class EpistemicRole(StrEnum):
    FACT = "FACT"
    INFERENCE = "INFERENCE"
    HYPOTHESIS = "HYPOTHESIS"


class DerivationRole(StrEnum):
    REPORTED = "REPORTED"
    PROVIDER_DERIVED = "PROVIDER_DERIVED"
    TI_DERIVED = "TI_DERIVED"


class ClaimRole(StrEnum):
    OBSERVED_REPORTED_VALUE = "OBSERVED_REPORTED_VALUE"
    ATTRIBUTED_STATEMENT = "ATTRIBUTED_STATEMENT"
    DERIVED_METRIC = "DERIVED_METRIC"
    INTERPRETATION = "INTERPRETATION"
    FORECAST = "FORECAST"


class EpistemicMappingStatus(StrEnum):
    MAPPED = "MAPPED"
    PARTIAL = "PARTIAL"
    UNMAPPED = "UNMAPPED"
    UNKNOWN = "UNKNOWN"


class ComparabilityStatus(StrEnum):
    EXACT = "EXACT"
    COMPARABLE_WITH_TRANSFORM = "COMPARABLE_WITH_TRANSFORM"
    NOT_COMPARABLE = "NOT_COMPARABLE"
    UNDETERMINED = "UNDETERMINED"


class DisputeCategory(StrEnum):
    FACTUAL_CONFLICT = "FACTUAL_CONFLICT"
    SEMANTIC_MISMATCH = "SEMANTIC_MISMATCH"
    TEMPORAL_DIFFERENCE = "TEMPORAL_DIFFERENCE"
    SCOPE_MISMATCH = "SCOPE_MISMATCH"
    INTERPRETIVE_DISAGREEMENT = "INTERPRETIVE_DISAGREEMENT"
    CROSS_DOMAIN_TENSION = "CROSS_DOMAIN_TENSION"
    FORECAST_DISAGREEMENT = "FORECAST_DISAGREEMENT"
    CONFIRMATION_DISCREPANCY = "CONFIRMATION_DISCREPANCY"


class DisputeState(StrEnum):
    DETECTED = "DETECTED"
    UNDER_REVIEW = "UNDER_REVIEW"
    CONFIRMED_CONFLICT = "CONFIRMED_CONFLICT"
    UNRESOLVED = "UNRESOLVED"
    NOT_COMPARABLE = "NOT_COMPARABLE"
    RESOLVED_BY_SCOPE = "RESOLVED_BY_SCOPE"
    RESOLVED_BY_REVISION = "RESOLVED_BY_REVISION"
    RESOLVED_BY_AUTHORITATIVE_FIELD = "RESOLVED_BY_AUTHORITATIVE_FIELD"
    SUPERSEDED = "SUPERSEDED"


class IndependenceRelation(StrEnum):
    SAME_ROOT = "SAME_ROOT"
    DERIVED_FROM = "DERIVED_FROM"
    LIKELY_DEPENDENT = "LIKELY_DEPENDENT"
    INDEPENDENT = "INDEPENDENT"
    UNKNOWN = "UNKNOWN"


class IndependenceDimension(StrEnum):
    PUBLICATION_LINEAGE = "PUBLICATION_LINEAGE"
    MEASUREMENT_ORIGIN = "MEASUREMENT_ORIGIN"
    ANALYTICAL_DERIVATION = "ANALYTICAL_DERIVATION"


class ConfirmationAdmissibility(StrEnum):
    ADMISSIBLE_MATCH = "ADMISSIBLE_MATCH"
    ADMISSIBLE_CONFLICT = "ADMISSIBLE_CONFLICT"
    NOT_ADMISSIBLE = "NOT_ADMISSIBLE"
    NOT_FOUND = "NOT_FOUND"
    UNAVAILABLE = "UNAVAILABLE"
    OUT_OF_COVERAGE = "OUT_OF_COVERAGE"
    AMBIGUOUS = "AMBIGUOUS"
    UNDETERMINED = "UNDETERMINED"


class Missingness(StrEnum):
    REQUIRED = "REQUIRED"
    OPTIONAL = "OPTIONAL"
