"""A3.6.1 provider-neutral market-intelligence fabric."""

from .enums import (
    AvailabilityBasis,
    CapabilitySupport,
    ContradictionResolution,
    DerivationClass,
    EnrichmentAction,
    EpistemicKind,
    EvidenceOutputType,
    GraphEdgeStatus,
    GraphNodeKind,
    GraphRelation,
    MarketIntelligenceCapability,
    PointInTimeQuality,
    ProviderFailureKind,
    ProviderResultStatus,
    ResearchDepth,
    ResearchStatus,
    RoutingMode,
    SemanticMappingQuality,
    SourceAuthority,
    authorities_for,
    authority_for,
)
from .graph import (
    EvidenceGraphEdge,
    EvidenceGraphNode,
    EvidenceGraphProvenance,
    SparseEvidenceGraph,
)
from .models import (
    AmbiguousEvidenceProjection,
    CanonicalEvidenceProjection,
    CapabilityRoutePolicy,
    ContradictionGroup,
    EnrichmentDecision,
    EvidenceCoverageAssessment,
    MarketIntelligenceRequest,
    MarketIntelligenceResearchPolicy,
    MarketIntelligenceResearchRequest,
    MarketIntelligenceResearchRun,
    MarketIntelligenceRun,
    MarketIntelligenceSynthesisContext,
    NormalizationRecord,
    NormalizedEvidenceBatch,
    ProviderCallAudit,
    ProviderCapabilityConstraints,
    ProviderCapabilityDeclaration,
    ProviderFailure,
    ProviderFetchResult,
    ProviderIdentity,
    ProviderManifest,
    ProviderNativeObservation,
)
from .normalization import RuleBasedNormalizer, SemanticRule, tapetide_normalizer
from .protocols import MarketIntelligenceNormalizer, MarketIntelligenceProvider
from .provider_routes import yahoo_secondary_route_policy
from .registry import MarketIntelligenceRegistry
from .research import (
    BusinessModelAssessment,
    CatalystRegister,
    CompanyResearchProfile,
    CompetitivePosition,
    ContradictingEvidence,
    CustomerExposure,
    IndustryStructureAssessment,
    InternationalExposure,
    ManagementEvidence,
    PolicyExposure,
    ResearchAssertion,
    ResearchComponent,
    ResearchGap,
    ResearchHypothesis,
    RiskRegister,
    SupplyChainExposure,
)
from .routing import MarketIntelligenceResearchController, MarketIntelligenceRouter

ResearchSynthesisContext = MarketIntelligenceSynthesisContext

__all__ = [
    "AvailabilityBasis",
    "AmbiguousEvidenceProjection",
    "BusinessModelAssessment",
    "CapabilityRoutePolicy",
    "CanonicalEvidenceProjection",
    "CapabilitySupport",
    "CatalystRegister",
    "CompanyResearchProfile",
    "CompetitivePosition",
    "ContradictingEvidence",
    "ContradictionGroup",
    "ContradictionResolution",
    "CustomerExposure",
    "DerivationClass",
    "EnrichmentAction",
    "EnrichmentDecision",
    "EpistemicKind",
    "EvidenceCoverageAssessment",
    "EvidenceGraphEdge",
    "EvidenceGraphNode",
    "EvidenceGraphProvenance",
    "EvidenceOutputType",
    "GraphEdgeStatus",
    "GraphNodeKind",
    "GraphRelation",
    "IndustryStructureAssessment",
    "InternationalExposure",
    "ManagementEvidence",
    "MarketIntelligenceCapability",
    "MarketIntelligenceNormalizer",
    "MarketIntelligenceProvider",
    "MarketIntelligenceRegistry",
    "MarketIntelligenceRequest",
    "MarketIntelligenceResearchController",
    "MarketIntelligenceResearchPolicy",
    "MarketIntelligenceResearchRequest",
    "MarketIntelligenceResearchRun",
    "MarketIntelligenceRouter",
    "MarketIntelligenceRun",
    "MarketIntelligenceSynthesisContext",
    "NormalizationRecord",
    "NormalizedEvidenceBatch",
    "PointInTimeQuality",
    "PolicyExposure",
    "ProviderCallAudit",
    "ProviderCapabilityConstraints",
    "ProviderCapabilityDeclaration",
    "ProviderFailure",
    "ProviderFailureKind",
    "ProviderFetchResult",
    "ProviderIdentity",
    "ProviderManifest",
    "ProviderNativeObservation",
    "ProviderResultStatus",
    "ResearchAssertion",
    "ResearchComponent",
    "ResearchDepth",
    "ResearchGap",
    "ResearchHypothesis",
    "ResearchStatus",
    "ResearchSynthesisContext",
    "RiskRegister",
    "RoutingMode",
    "RuleBasedNormalizer",
    "SemanticMappingQuality",
    "SemanticRule",
    "SourceAuthority",
    "SparseEvidenceGraph",
    "SupplyChainExposure",
    "authorities_for",
    "authority_for",
    "tapetide_normalizer",
    "yahoo_secondary_route_policy",
]
