"""Stable A3.6 macro-context interpretation states."""

from enum import StrEnum


class MarketRiskRegime(StrEnum):
    RISK_ON = "RISK_ON"
    MILD_RISK_ON = "MILD_RISK_ON"
    NEUTRAL = "NEUTRAL"
    MILD_RISK_OFF = "MILD_RISK_OFF"
    RISK_OFF = "RISK_OFF"
    STRESS = "STRESS"
    MIXED = "MIXED"
    UNKNOWN = "UNKNOWN"


class MacroVolatilityRegime(StrEnum):
    LOW = "LOW"
    NORMAL = "NORMAL"
    ELEVATED = "ELEVATED"
    HIGH = "HIGH"
    EXTREME = "EXTREME"
    COMPRESSING = "COMPRESSING"
    EXPANDING = "EXPANDING"
    UNKNOWN = "UNKNOWN"


class RateRegime(StrEnum):
    EASING = "EASING"
    LOW_AND_STABLE = "LOW_AND_STABLE"
    NEUTRAL = "NEUTRAL"
    TIGHTENING = "TIGHTENING"
    HIGH_AND_STABLE = "HIGH_AND_STABLE"
    VOLATILE = "VOLATILE"
    UNKNOWN = "UNKNOWN"


class CurrencyState(StrEnum):
    APPRECIATING = "APPRECIATING"
    STABLE = "STABLE"
    DEPRECIATING = "DEPRECIATING"
    VOLATILE = "VOLATILE"
    UNKNOWN = "UNKNOWN"


class CommodityContextState(StrEnum):
    FAVORABLE = "FAVORABLE"
    NEUTRAL = "NEUTRAL"
    ADVERSE = "ADVERSE"
    VOLATILE = "VOLATILE"
    UNKNOWN = "UNKNOWN"


class SubjectSensitivityState(StrEnum):
    MAPPED = "MAPPED"
    PARTIAL = "PARTIAL"
    UNKNOWN = "UNKNOWN"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    MAPPING_REQUIRED = "MAPPING_REQUIRED"


class MacroReasonCode(StrEnum):
    RISK_ON_CONTEXT = "RISK_ON_CONTEXT"
    RISK_OFF_CONTEXT = "RISK_OFF_CONTEXT"
    MARKET_STRESS = "MARKET_STRESS"
    VOLATILITY_ELEVATED = "VOLATILITY_ELEVATED"
    RATES_TIGHTENING = "RATES_TIGHTENING"
    RATES_EASING = "RATES_EASING"
    CURRENCY_FAVORABLE = "CURRENCY_FAVORABLE"
    CURRENCY_ADVERSE = "CURRENCY_ADVERSE"
    COMMODITY_FAVORABLE = "COMMODITY_FAVORABLE"
    COMMODITY_ADVERSE = "COMMODITY_ADVERSE"
    MACRO_SENSITIVITY_UNKNOWN = "MACRO_SENSITIVITY_UNKNOWN"
    MACRO_CONFLICT = "MACRO_CONFLICT"
    MACRO_EVIDENCE_PARTIAL = "MACRO_EVIDENCE_PARTIAL"
    MACRO_EVIDENCE_STALE = "MACRO_EVIDENCE_STALE"
    MACRO_EVIDENCE_INSUFFICIENT = "MACRO_EVIDENCE_INSUFFICIENT"
