"""Stable provider-neutral event, source, and interpretation vocabularies."""

from enum import StrEnum


class EventFamily(StrEnum):
    CORPORATE_RESULTS = "CORPORATE_RESULTS"
    GUIDANCE = "GUIDANCE"
    DIVIDEND = "DIVIDEND"
    BUYBACK = "BUYBACK"
    BONUS_SPLIT = "BONUS_SPLIT"
    CAPITAL_RAISE = "CAPITAL_RAISE"
    M_AND_A = "M_AND_A"
    ORDER_CONTRACT = "ORDER_CONTRACT"
    CAPEX = "CAPEX"
    MANAGEMENT_CHANGE = "MANAGEMENT_CHANGE"
    PROMOTER_OWNERSHIP = "PROMOTER_OWNERSHIP"
    PLEDGE = "PLEDGE"
    REGULATORY = "REGULATORY"
    LITIGATION = "LITIGATION"
    CREDIT_RATING = "CREDIT_RATING"
    PRODUCT_LAUNCH = "PRODUCT_LAUNCH"
    BUSINESS_EXPANSION = "BUSINESS_EXPANSION"
    CUSTOMER_WIN_LOSS = "CUSTOMER_WIN_LOSS"
    SUPPLY_CHAIN = "SUPPLY_CHAIN"
    SECTOR_EVENT = "SECTOR_EVENT"
    GOVERNMENT_POLICY = "GOVERNMENT_POLICY"
    MACRO_EVENT = "MACRO_EVENT"
    GEOPOLITICAL = "GEOPOLITICAL"
    EXCHANGE_FILING = "EXCHANGE_FILING"
    OTHER = "OTHER"


class EventType(StrEnum):
    RESULTS_REPORTED = "RESULTS_REPORTED"
    GUIDANCE_RAISED = "GUIDANCE_RAISED"
    GUIDANCE_CUT = "GUIDANCE_CUT"
    GUIDANCE_REAFFIRMED = "GUIDANCE_REAFFIRMED"
    DIVIDEND_DECLARED = "DIVIDEND_DECLARED"
    BUYBACK_APPROVED = "BUYBACK_APPROVED"
    SPLIT_OR_BONUS_APPROVED = "SPLIT_OR_BONUS_APPROVED"
    CAPITAL_RAISE_APPROVED = "CAPITAL_RAISE_APPROVED"
    ACQUISITION_ANNOUNCED = "ACQUISITION_ANNOUNCED"
    DIVESTMENT_ANNOUNCED = "DIVESTMENT_ANNOUNCED"
    ORDER_AWARDED = "ORDER_AWARDED"
    ORDER_LOST = "ORDER_LOST"
    CAPEX_ANNOUNCED = "CAPEX_ANNOUNCED"
    CAPEX_DELAYED = "CAPEX_DELAYED"
    MANAGEMENT_APPOINTED = "MANAGEMENT_APPOINTED"
    MANAGEMENT_RESIGNED = "MANAGEMENT_RESIGNED"
    PROMOTER_TRANSACTION = "PROMOTER_TRANSACTION"
    PLEDGE_CREATED = "PLEDGE_CREATED"
    PLEDGE_RELEASED = "PLEDGE_RELEASED"
    REGULATORY_APPROVAL = "REGULATORY_APPROVAL"
    REGULATORY_ACTION = "REGULATORY_ACTION"
    LITIGATION_FILED = "LITIGATION_FILED"
    LITIGATION_RESOLVED = "LITIGATION_RESOLVED"
    RATING_UPGRADE = "RATING_UPGRADE"
    RATING_DOWNGRADE = "RATING_DOWNGRADE"
    PRODUCT_LAUNCHED = "PRODUCT_LAUNCHED"
    EXPANSION_ANNOUNCED = "EXPANSION_ANNOUNCED"
    CUSTOMER_WON = "CUSTOMER_WON"
    CUSTOMER_LOST = "CUSTOMER_LOST"
    SUPPLY_DISRUPTION = "SUPPLY_DISRUPTION"
    POLICY_ANNOUNCED = "POLICY_ANNOUNCED"
    FILING_PUBLISHED = "FILING_PUBLISHED"
    OTHER = "OTHER"
    UNKNOWN = "UNKNOWN"


class EventSourceClass(StrEnum):
    EXCHANGE_FILING = "EXCHANGE_FILING"
    REGULATORY_FILING = "REGULATORY_FILING"
    COMPANY_RELEASE = "COMPANY_RELEASE"
    EARNINGS_TRANSCRIPT = "EARNINGS_TRANSCRIPT"
    OFFICIAL_GOVERNMENT = "OFFICIAL_GOVERNMENT"
    TRUSTED_NEWS = "TRUSTED_NEWS"
    LICENSED_AGGREGATOR = "LICENSED_AGGREGATOR"
    OTHER = "OTHER"
    UNKNOWN = "UNKNOWN"


class EntityKind(StrEnum):
    COMPANY = "COMPANY"
    INSTRUMENT = "INSTRUMENT"
    SECTOR = "SECTOR"
    INDUSTRY = "INDUSTRY"
    INDEX = "INDEX"
    GOVERNMENT = "GOVERNMENT"
    OTHER = "OTHER"


class EntityMappingStatus(StrEnum):
    EXACT = "EXACT"
    EXPLICIT_RELATED = "EXPLICIT_RELATED"
    UNRESOLVED = "UNRESOLVED"


class EventRelevance(StrEnum):
    DIRECT = "DIRECT"
    HIGH = "HIGH"
    MODERATE = "MODERATE"
    LOW = "LOW"
    INCIDENTAL = "INCIDENTAL"
    UNKNOWN = "UNKNOWN"


class EventMateriality(StrEnum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MODERATE = "MODERATE"
    LOW = "LOW"
    IMMATERIAL = "IMMATERIAL"
    UNKNOWN = "UNKNOWN"


class EventNovelty(StrEnum):
    NEW = "NEW"
    UPDATE = "UPDATE"
    REPEAT = "REPEAT"
    DUPLICATE = "DUPLICATE"
    CORRECTION = "CORRECTION"
    UNKNOWN = "UNKNOWN"


class EventStatus(StrEnum):
    ANNOUNCED = "ANNOUNCED"
    CONFIRMED = "CONFIRMED"
    ONGOING = "ONGOING"
    COMPLETED = "COMPLETED"
    DELAYED = "DELAYED"
    CANCELLED = "CANCELLED"
    DISPUTED = "DISPUTED"
    UNKNOWN = "UNKNOWN"


class StructuredFactKind(StrEnum):
    TEXT = "TEXT"
    INTEGER = "INTEGER"
    NUMBER = "NUMBER"
    BOOLEAN = "BOOLEAN"
    DATE = "DATE"


class CatalystDirection(StrEnum):
    STRONGLY_POSITIVE = "STRONGLY_POSITIVE"
    POSITIVE = "POSITIVE"
    MILDLY_POSITIVE = "MILDLY_POSITIVE"
    NEUTRAL = "NEUTRAL"
    MIXED = "MIXED"
    MILDLY_NEGATIVE = "MILDLY_NEGATIVE"
    NEGATIVE = "NEGATIVE"
    STRONGLY_NEGATIVE = "STRONGLY_NEGATIVE"
    UNKNOWN = "UNKNOWN"


class CatalystStrength(StrEnum):
    HIGH = "HIGH"
    MODERATE = "MODERATE"
    LOW = "LOW"
    IMMATERIAL = "IMMATERIAL"
    UNKNOWN = "UNKNOWN"


class CatalystHorizon(StrEnum):
    IMMEDIATE = "IMMEDIATE"
    SHORT_TERM = "SHORT_TERM"
    MEDIUM_TERM = "MEDIUM_TERM"
    LONG_TERM = "LONG_TERM"
    MULTI_HORIZON = "MULTI_HORIZON"
    UNKNOWN = "UNKNOWN"


class SourceQualityState(StrEnum):
    PRIMARY = "PRIMARY"
    OFFICIAL = "OFFICIAL"
    TRUSTED_SECONDARY = "TRUSTED_SECONDARY"
    OTHER = "OTHER"
    UNKNOWN = "UNKNOWN"


class ContradictionState(StrEnum):
    NONE = "NONE"
    SOURCE_CONFLICT = "SOURCE_CONFLICT"
    CORRECTED = "CORRECTED"
    DISPUTED = "DISPUTED"


class ExecutionRiskState(StrEnum):
    HIGH = "HIGH"
    MODERATE = "MODERATE"
    LOW = "LOW"
    UNKNOWN = "UNKNOWN"
