"""Stable technical-interpretation vocabulary for the A3.3 specialist."""

from enum import StrEnum


class TrendState(StrEnum):
    STRONG_UPTREND = "STRONG_UPTREND"
    MODERATE_UPTREND = "MODERATE_UPTREND"
    WEAK_UPTREND = "WEAK_UPTREND"
    SIDEWAYS = "SIDEWAYS"
    WEAK_DOWNTREND = "WEAK_DOWNTREND"
    MODERATE_DOWNTREND = "MODERATE_DOWNTREND"
    STRONG_DOWNTREND = "STRONG_DOWNTREND"
    MIXED = "MIXED"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"


class MomentumState(StrEnum):
    ACCELERATING = "ACCELERATING"
    POSITIVE = "POSITIVE"
    FADING_POSITIVE = "FADING_POSITIVE"
    NEUTRAL = "NEUTRAL"
    FADING_NEGATIVE = "FADING_NEGATIVE"
    NEGATIVE = "NEGATIVE"
    ACCELERATING_NEGATIVE = "ACCELERATING_NEGATIVE"
    MIXED = "MIXED"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"


class StructureState(StrEnum):
    BULLISH_STRUCTURE = "BULLISH_STRUCTURE"
    BEARISH_STRUCTURE = "BEARISH_STRUCTURE"
    RANGE_BOUND = "RANGE_BOUND"
    COMPRESSION = "COMPRESSION"
    EXPANSION = "EXPANSION"
    BREAKOUT_ATTEMPT = "BREAKOUT_ATTEMPT"
    BREAKDOWN_ATTEMPT = "BREAKDOWN_ATTEMPT"
    MIXED = "MIXED"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"


class BreakoutState(StrEnum):
    CONFIRMED_CLOSE_BREAKOUT = "CONFIRMED_CLOSE_BREAKOUT"
    WICK_ONLY_BREAKOUT = "WICK_ONLY_BREAKOUT"
    CONFIRMED_CLOSE_BREAKDOWN = "CONFIRMED_CLOSE_BREAKDOWN"
    WICK_ONLY_BREAKDOWN = "WICK_ONLY_BREAKDOWN"
    NO_BREAK = "NO_BREAK"
    CONFLICTED = "CONFLICTED"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"


class ParticipationState(StrEnum):
    CONFIRMS_POSITIVE = "CONFIRMS_POSITIVE"
    CONFIRMS_NEGATIVE = "CONFIRMS_NEGATIVE"
    CONTRADICTS_POSITIVE_MOVE = "CONTRADICTS_POSITIVE_MOVE"
    CONTRADICTS_NEGATIVE_MOVE = "CONTRADICTS_NEGATIVE_MOVE"
    NEUTRAL = "NEUTRAL"
    UNUSUALLY_HIGH = "UNUSUALLY_HIGH"
    UNUSUALLY_LOW = "UNUSUALLY_LOW"
    NOISY = "NOISY"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"


class VolatilityState(StrEnum):
    LOW = "LOW"
    NORMAL = "NORMAL"
    ELEVATED = "ELEVATED"
    EXTREME = "EXTREME"
    COMPRESSING = "COMPRESSING"
    EXPANDING = "EXPANDING"
    MIXED = "MIXED"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"


class MultiTimeframeState(StrEnum):
    ALIGNED_POSITIVE = "ALIGNED_POSITIVE"
    ALIGNED_NEGATIVE = "ALIGNED_NEGATIVE"
    MIXED = "MIXED"
    CONFLICTED = "CONFLICTED"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"


class ExtensionState(StrEnum):
    EARLY = "EARLY"
    DEVELOPING = "DEVELOPING"
    MATURE = "MATURE"
    EXTENDED = "EXTENDED"
    EXHAUSTION_RISK = "EXHAUSTION_RISK"
    UNKNOWN = "UNKNOWN"


class RemainingRoomState(StrEnum):
    LARGE = "LARGE"
    MODERATE = "MODERATE"
    LIMITED = "LIMITED"
    MINIMAL = "MINIMAL"
    UNKNOWN = "UNKNOWN"


class TechnicalReasonCode(StrEnum):
    TREND_UP_ALIGNED = "TREND_UP_ALIGNED"
    TREND_DOWN_ALIGNED = "TREND_DOWN_ALIGNED"
    TREND_WEAK = "TREND_WEAK"
    MOMENTUM_POSITIVE = "MOMENTUM_POSITIVE"
    MOMENTUM_FADING = "MOMENTUM_FADING"
    MOMENTUM_NEGATIVE = "MOMENTUM_NEGATIVE"
    BREAKOUT_CONFIRMED_CLOSE = "BREAKOUT_CONFIRMED_CLOSE"
    BREAKOUT_WICK_ONLY = "BREAKOUT_WICK_ONLY"
    BREAKDOWN_CONFIRMED_CLOSE = "BREAKDOWN_CONFIRMED_CLOSE"
    BREAKDOWN_WICK_ONLY = "BREAKDOWN_WICK_ONLY"
    VOLUME_CONFIRMS = "VOLUME_CONFIRMS"
    VOLUME_DIVERGES = "VOLUME_DIVERGES"
    MTF_ALIGNED = "MTF_ALIGNED"
    MTF_MIXED = "MTF_MIXED"
    VOLATILITY_ELEVATED = "VOLATILITY_ELEVATED"
    RANGE_COMPRESSED = "RANGE_COMPRESSED"
    RANGE_EXPANDING = "RANGE_EXPANDING"
    EXTENDED_FROM_MEAN = "EXTENDED_FROM_MEAN"
    EXHAUSTION_RISK = "EXHAUSTION_RISK"
    LIMITED_ROOM_TO_RESISTANCE = "LIMITED_ROOM_TO_RESISTANCE"
    LIMITED_ROOM_TO_SUPPORT = "LIMITED_ROOM_TO_SUPPORT"
    TECHNICAL_CONFLICT = "TECHNICAL_CONFLICT"
    OPTIONAL_EVIDENCE_MISSING = "OPTIONAL_EVIDENCE_MISSING"
    CORE_EVIDENCE_MISSING = "CORE_EVIDENCE_MISSING"
    EVIDENCE_PARTIAL = "EVIDENCE_PARTIAL"
    EVIDENCE_STALE = "EVIDENCE_STALE"
