"""Stable A3.6 sector/rotation interpretation states."""

from enum import StrEnum


class SectorState(StrEnum):
    STRONG = "STRONG"
    SUPPORTIVE = "SUPPORTIVE"
    NEUTRAL = "NEUTRAL"
    WEAK = "WEAK"
    VERY_WEAK = "VERY_WEAK"
    MIXED = "MIXED"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"


class RotationState(StrEnum):
    ROTATING_IN = "ROTATING_IN"
    LEADING = "LEADING"
    IMPROVING = "IMPROVING"
    NEUTRAL = "NEUTRAL"
    WEAKENING = "WEAKENING"
    LAGGING = "LAGGING"
    ROTATING_OUT = "ROTATING_OUT"
    MIXED = "MIXED"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"


class SectorBreadthState(StrEnum):
    STRONG = "STRONG"
    HEALTHY = "HEALTHY"
    MIXED = "MIXED"
    WEAK = "WEAK"
    UNKNOWN = "UNKNOWN"


class SectorParticipationState(StrEnum):
    BROAD = "BROAD"
    NORMAL = "NORMAL"
    NARROW = "NARROW"
    UNKNOWN = "UNKNOWN"


class SectorConcentrationState(StrEnum):
    BROAD_LEADERSHIP = "BROAD_LEADERSHIP"
    CONCENTRATED_LEADERSHIP = "CONCENTRATED_LEADERSHIP"
    BROAD_WEAKNESS = "BROAD_WEAKNESS"
    CONCENTRATED_WEAKNESS = "CONCENTRATED_WEAKNESS"
    UNKNOWN = "UNKNOWN"


class SubjectSectorState(StrEnum):
    OUTPERFORMS_SECTOR = "OUTPERFORMS_SECTOR"
    INLINE_WITH_SECTOR = "INLINE_WITH_SECTOR"
    LAGS_SECTOR = "LAGS_SECTOR"
    UNKNOWN = "UNKNOWN"


class SectorReasonCode(StrEnum):
    SECTOR_LEADING = "SECTOR_LEADING"
    SECTOR_IMPROVING = "SECTOR_IMPROVING"
    SECTOR_ROTATING_IN = "SECTOR_ROTATING_IN"
    SECTOR_WEAKENING = "SECTOR_WEAKENING"
    SECTOR_LAGGING = "SECTOR_LAGGING"
    SECTOR_ROTATING_OUT = "SECTOR_ROTATING_OUT"
    SECTOR_BREADTH_STRONG = "SECTOR_BREADTH_STRONG"
    SECTOR_BREADTH_WEAK = "SECTOR_BREADTH_WEAK"
    SECTOR_LEADERSHIP_CONCENTRATED = "SECTOR_LEADERSHIP_CONCENTRATED"
    SUBJECT_OUTPERFORMS_SECTOR = "SUBJECT_OUTPERFORMS_SECTOR"
    SUBJECT_LAGS_SECTOR = "SUBJECT_LAGS_SECTOR"
    SECTOR_EVENT_SUPPORT = "SECTOR_EVENT_SUPPORT"
    SECTOR_EVENT_CONFLICT = "SECTOR_EVENT_CONFLICT"
    SECTOR_MAPPING_MISSING = "SECTOR_MAPPING_MISSING"
    SECTOR_MAPPING_AMBIGUOUS = "SECTOR_MAPPING_AMBIGUOUS"
    SECTOR_EVIDENCE_PARTIAL = "SECTOR_EVIDENCE_PARTIAL"
    SECTOR_EVIDENCE_STALE = "SECTOR_EVIDENCE_STALE"
