"""Stable A3.4 company-quality interpretation states and reasons."""

from enum import StrEnum


class GrowthState(StrEnum):
    STRONG_GROWTH = "STRONG_GROWTH"
    HEALTHY_GROWTH = "HEALTHY_GROWTH"
    MODERATE_GROWTH = "MODERATE_GROWTH"
    STAGNANT = "STAGNANT"
    DECLINING = "DECLINING"
    VOLATILE = "VOLATILE"
    MIXED = "MIXED"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"


class ProfitabilityState(StrEnum):
    STRONG = "STRONG"
    HEALTHY = "HEALTHY"
    AVERAGE = "AVERAGE"
    WEAK = "WEAK"
    DETERIORATING = "DETERIORATING"
    MIXED = "MIXED"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"


class MarginState(StrEnum):
    STRONG = "STRONG"
    HEALTHY = "HEALTHY"
    STABLE = "STABLE"
    EXPANDING = "EXPANDING"
    CONTRACTING = "CONTRACTING"
    NEGATIVE = "NEGATIVE"
    MIXED = "MIXED"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"


class CapitalEfficiencyState(StrEnum):
    STRONG = "STRONG"
    HEALTHY = "HEALTHY"
    AVERAGE = "AVERAGE"
    WEAK = "WEAK"
    DETERIORATING = "DETERIORATING"
    LEVERAGE_DRIVEN = "LEVERAGE_DRIVEN"
    SECTOR_POLICY_REQUIRED = "SECTOR_POLICY_REQUIRED"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"


class BalanceSheetState(StrEnum):
    VERY_STRONG = "VERY_STRONG"
    STRONG = "STRONG"
    ADEQUATE = "ADEQUATE"
    LEVERAGED = "LEVERAGED"
    WEAK = "WEAK"
    DISTRESSED_RISK = "DISTRESSED_RISK"
    SECTOR_POLICY_REQUIRED = "SECTOR_POLICY_REQUIRED"
    UNKNOWN = "UNKNOWN"


class CashFlowState(StrEnum):
    STRONG = "STRONG"
    HEALTHY = "HEALTHY"
    ADEQUATE = "ADEQUATE"
    WEAK = "WEAK"
    NEGATIVE = "NEGATIVE"
    VOLATILE = "VOLATILE"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"


class EarningsQualityState(StrEnum):
    HIGH = "HIGH"
    GOOD = "GOOD"
    ADEQUATE = "ADEQUATE"
    WEAK = "WEAK"
    PROFIT_CASHFLOW_DIVERGENCE = "PROFIT_CASHFLOW_DIVERGENCE"
    MIXED = "MIXED"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"


class ValuationState(StrEnum):
    CHEAP = "CHEAP"
    REASONABLE = "REASONABLE"
    FAIR = "FAIR"
    EXPENSIVE = "EXPENSIVE"
    VERY_EXPENSIVE = "VERY_EXPENSIVE"
    NOT_MEANINGFUL = "NOT_MEANINGFUL"
    SECTOR_POLICY_REQUIRED = "SECTOR_POLICY_REQUIRED"
    UNKNOWN = "UNKNOWN"


class StabilityState(StrEnum):
    HIGH = "HIGH"
    STABLE = "STABLE"
    VARIABLE = "VARIABLE"
    VOLATILE = "VOLATILE"
    DETERIORATING = "DETERIORATING"
    UNKNOWN = "UNKNOWN"


class OwnershipEvidenceState(StrEnum):
    AVAILABLE = "AVAILABLE"
    PARTIAL = "PARTIAL"
    ELEVATED_DISCLOSED_RISK = "ELEVATED_DISCLOSED_RISK"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"


class FundamentalMomentumState(StrEnum):
    IMPROVING = "IMPROVING"
    STABLE = "STABLE"
    DETERIORATING = "DETERIORATING"
    MIXED = "MIXED"
    UNKNOWN = "UNKNOWN"


class CompanyQualityState(StrEnum):
    HIGH_QUALITY = "HIGH_QUALITY"
    GOOD_QUALITY = "GOOD_QUALITY"
    AVERAGE = "AVERAGE"
    WEAK = "WEAK"
    DETERIORATING = "DETERIORATING"
    MIXED = "MIXED"
    SECTOR_POLICY_REQUIRED = "SECTOR_POLICY_REQUIRED"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"


class FundamentalReasonCode(StrEnum):
    REVENUE_GROWTH_STRONG = "REVENUE_GROWTH_STRONG"
    REVENUE_GROWTH_DECELERATING = "REVENUE_GROWTH_DECELERATING"
    PROFIT_GROWTH_STRONG = "PROFIT_GROWTH_STRONG"
    PROFIT_DECLINING = "PROFIT_DECLINING"
    MARGIN_EXPANDING = "MARGIN_EXPANDING"
    MARGIN_CONTRACTING = "MARGIN_CONTRACTING"
    ROCE_STRONG = "ROCE_STRONG"
    ROCE_DETERIORATING = "ROCE_DETERIORATING"
    LEVERAGE_LOW = "LEVERAGE_LOW"
    LEVERAGE_HIGH = "LEVERAGE_HIGH"
    INTEREST_COVERAGE_WEAK = "INTEREST_COVERAGE_WEAK"
    OPERATING_CASH_FLOW_STRONG = "OPERATING_CASH_FLOW_STRONG"
    PROFIT_CASHFLOW_DIVERGENCE = "PROFIT_CASHFLOW_DIVERGENCE"
    FCF_CONSISTENT = "FCF_CONSISTENT"
    VALUATION_ELEVATED = "VALUATION_ELEVATED"
    VALUATION_REASONABLE = "VALUATION_REASONABLE"
    DILUTION_RISK = "DILUTION_RISK"
    PROMOTER_PLEDGE_ELEVATED = "PROMOTER_PLEDGE_ELEVATED"
    FUNDAMENTAL_EVIDENCE_PARTIAL = "FUNDAMENTAL_EVIDENCE_PARTIAL"
    FUNDAMENTAL_EVIDENCE_STALE = "FUNDAMENTAL_EVIDENCE_STALE"
    FUNDAMENTAL_EVIDENCE_INSUFFICIENT = "FUNDAMENTAL_EVIDENCE_INSUFFICIENT"
    SECTOR_POLICY_REQUIRED = "SECTOR_POLICY_REQUIRED"
    FUNDAMENTAL_CONFLICT = "FUNDAMENTAL_CONFLICT"
