"""Closed FF realization, generation and qualification vocabulary."""

from enum import StrEnum


class ForecastRealizationMode(StrEnum):
    ACTUAL_ISSUANCE = "ACTUAL_ISSUANCE"
    SIMULATED_ISSUANCE = "SIMULATED_ISSUANCE"


class ForecastStatus(StrEnum):
    GENERATED = "GENERATED"
    ABSTAINED = "ABSTAINED"
    UNSUPPORTED = "UNSUPPORTED"
    UNAVAILABLE = "UNAVAILABLE"
    FAILED = "FAILED"


class DataBasis(StrEnum):
    SYNTHETIC_FIXTURE = "SYNTHETIC_FIXTURE"
    QUALIFIED_CAPTURE = "QUALIFIED_CAPTURE"


class KnowledgeBasis(StrEnum):
    CAPTURED_AS_KNOWN = "CAPTURED_AS_KNOWN"
    QUALIFIED_HISTORICAL_AVAILABILITY = "QUALIFIED_HISTORICAL_AVAILABILITY"


class QualificationStatus(StrEnum):
    QUALIFIED = "QUALIFIED"
    MISSING = "MISSING"
    PARTIAL = "PARTIAL"
    STALE = "STALE"
    AMBIGUOUS = "AMBIGUOUS"


class ForecastReason(StrEnum):
    SCOPE_UNSUPPORTED = "SCOPE_UNSUPPORTED"
    TARGET_SESSION_UNRESOLVED = "TARGET_SESSION_UNRESOLVED"
    EVIDENCE_MISSING = "EVIDENCE_MISSING"
    EVIDENCE_STALE = "EVIDENCE_STALE"
    EVIDENCE_UNQUALIFIED = "EVIDENCE_UNQUALIFIED"
    CALENDAR_UNQUALIFIED = "CALENDAR_UNQUALIFIED"
    ACTION_COVERAGE_UNKNOWN = "ACTION_COVERAGE_UNKNOWN"
    ACTION_AFFECTED = "ACTION_AFFECTED"
    KNOWLEDGE_CUTOFF_VIOLATION = "KNOWLEDGE_CUTOFF_VIOLATION"
    TEMPORAL_INELIGIBLE = "TEMPORAL_INELIGIBLE"
    EMPIRICAL_PROFILE_NOT_ENABLED = "EMPIRICAL_PROFILE_NOT_ENABLED"
    ARTIFACT_UNAVAILABLE = "ARTIFACT_UNAVAILABLE"
    POLICY_ABSTENTION = "POLICY_ABSTENTION"
    INTERNAL_EXECUTION_FAILURE = "INTERNAL_EXECUTION_FAILURE"
    HISTORY_SUPPORT_INSUFFICIENT = "HISTORY_SUPPORT_INSUFFICIENT"
    LOCAL_DEADLINE_EXCEEDED = "LOCAL_DEADLINE_EXCEEDED"


class PopulationDisposition(StrEnum):
    INCLUDED = "INCLUDED"
    EXCLUDED = "EXCLUDED"
    NOT_EVALUABLE = "NOT_EVALUABLE"
