"""Stable A3.7 derivatives, opportunity-quality, and risk states."""

from enum import StrEnum


class DerivativesVolatilityState(StrEnum):
    ELEVATED = "ELEVATED"
    MODERATE = "MODERATE"
    COMPRESSED = "COMPRESSED"
    UNKNOWN = "UNKNOWN"


class DerivativesPositioningState(StrEnum):
    SUPPORTIVE_CONTEXT = "SUPPORTIVE_CONTEXT"
    ADVERSE_CONTEXT = "ADVERSE_CONTEXT"
    BALANCED = "BALANCED"
    CONFLICTED = "CONFLICTED"
    UNKNOWN = "UNKNOWN"


class DerivativesLiquidityState(StrEnum):
    ADEQUATE = "ADEQUATE"
    MIXED = "MIXED"
    WEAK = "WEAK"
    UNKNOWN = "UNKNOWN"


class DerivativesParticipationState(StrEnum):
    PRESENT = "PRESENT"
    ABSENT = "ABSENT"
    UNKNOWN = "UNKNOWN"


class CrowdingState(StrEnum):
    CONCENTRATED = "CONCENTRATED"
    DISTRIBUTED = "DISTRIBUTED"
    UNKNOWN = "UNKNOWN"


class ExpiryProximityState(StrEnum):
    IMMINENT = "IMMINENT"
    NEAR = "NEAR"
    NOT_NEAR = "NOT_NEAR"
    UNKNOWN = "UNKNOWN"


class ConfirmationState(StrEnum):
    CONFIRMS = "CONFIRMS"
    CONFLICTS = "CONFLICTS"
    NEUTRAL = "NEUTRAL"
    UNKNOWN = "UNKNOWN"


class DerivativesReasonCode(StrEnum):
    DERIVATIVES_IV_ELEVATED = "DERIVATIVES_IV_ELEVATED"
    DERIVATIVES_IV_COMPRESSED = "DERIVATIVES_IV_COMPRESSED"
    DERIVATIVES_IV_MODERATE = "DERIVATIVES_IV_MODERATE"
    DERIVATIVES_OI_SUPPORTIVE_CONTEXT = "DERIVATIVES_OI_SUPPORTIVE_CONTEXT"
    DERIVATIVES_OI_ADVERSE_CONTEXT = "DERIVATIVES_OI_ADVERSE_CONTEXT"
    DERIVATIVES_OI_BALANCED = "DERIVATIVES_OI_BALANCED"
    DERIVATIVES_CONFLICTED = "DERIVATIVES_CONFLICTED"
    DERIVATIVES_OI_CONCENTRATED = "DERIVATIVES_OI_CONCENTRATED"
    DERIVATIVES_LIQUIDITY_ADEQUATE = "DERIVATIVES_LIQUIDITY_ADEQUATE"
    DERIVATIVES_LIQUIDITY_WEAK = "DERIVATIVES_LIQUIDITY_WEAK"
    DERIVATIVES_PARTICIPATION_ABSENT = "DERIVATIVES_PARTICIPATION_ABSENT"
    DERIVATIVES_EXPIRY_NEAR = "DERIVATIVES_EXPIRY_NEAR"
    DERIVATIVES_UNDERLYING_CONFLICT = "DERIVATIVES_UNDERLYING_CONFLICT"
    DERIVATIVES_EVIDENCE_STALE = "DERIVATIVES_EVIDENCE_STALE"
    DERIVATIVES_EVIDENCE_INSUFFICIENT = "DERIVATIVES_EVIDENCE_INSUFFICIENT"


class OpportunityQualityState(StrEnum):
    STRONG = "STRONG"
    GOOD = "GOOD"
    MIXED = "MIXED"
    WEAK = "WEAK"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"


class OpportunityMaturityState(StrEnum):
    EARLY = "EARLY"
    DEVELOPING = "DEVELOPING"
    MATURE = "MATURE"
    UNKNOWN = "UNKNOWN"


class RemainingRoomQuality(StrEnum):
    SUFFICIENT = "SUFFICIENT"
    LIMITED = "LIMITED"
    UNKNOWN = "UNKNOWN"


class OpportunityReasonCode(StrEnum):
    OPPORTUNITY_EARLY = "OPPORTUNITY_EARLY"
    OPPORTUNITY_MATURE = "OPPORTUNITY_MATURE"
    OPPORTUNITY_EXTENDED = "OPPORTUNITY_EXTENDED"
    OPPORTUNITY_ROOM_SUFFICIENT = "OPPORTUNITY_ROOM_SUFFICIENT"
    OPPORTUNITY_ROOM_LIMITED = "OPPORTUNITY_ROOM_LIMITED"
    OPPORTUNITY_CROSS_DOMAIN_SUPPORT = "OPPORTUNITY_CROSS_DOMAIN_SUPPORT"
    OPPORTUNITY_CROSS_DOMAIN_CONFLICT = "OPPORTUNITY_CROSS_DOMAIN_CONFLICT"
    OPPORTUNITY_SETUP_CLEAN = "OPPORTUNITY_SETUP_CLEAN"
    OPPORTUNITY_SETUP_MIXED = "OPPORTUNITY_SETUP_MIXED"
    OPPORTUNITY_BASELINE_NO_TRADE = "OPPORTUNITY_BASELINE_NO_TRADE"
    EVENT_RISK_NEAR = "EVENT_RISK_NEAR"
    EVIDENCE_STALE = "EVIDENCE_STALE"
    EVIDENCE_INSUFFICIENT = "EVIDENCE_INSUFFICIENT"


class OpportunityRiskLevel(StrEnum):
    LOW = "LOW"
    MODERATE = "MODERATE"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"


class RiskReasonCode(StrEnum):
    RISK_OVEREXTENDED = "RISK_OVEREXTENDED"
    RISK_ROOM_LIMITED = "RISK_ROOM_LIMITED"
    RISK_PARTICIPATION_WEAK = "RISK_PARTICIPATION_WEAK"
    RISK_VOLATILITY_SHOCK = "RISK_VOLATILITY_SHOCK"
    RISK_EVENT_GAP = "RISK_EVENT_GAP"
    RISK_EXPIRY_PROXIMITY = "RISK_EXPIRY_PROXIMITY"
    RISK_CONTEXT_CONFLICT = "RISK_CONTEXT_CONFLICT"
    RISK_FUNDAMENTAL_FRAGILITY = "RISK_FUNDAMENTAL_FRAGILITY"
    RISK_DERIVATIVES_CROWDING = "RISK_DERIVATIVES_CROWDING"
    RISK_LIQUIDITY_WEAK = "RISK_LIQUIDITY_WEAK"
    CONTRADICTION_HIGH = "CONTRADICTION_HIGH"
    EVIDENCE_STALE = "EVIDENCE_STALE"
    EVIDENCE_INSUFFICIENT = "EVIDENCE_INSUFFICIENT"
