"""Closed deterministic A4 vocabularies; none imply trading action."""

from enum import StrEnum


class PremiseRole(StrEnum):
    FACT = "FACT"
    INFERENCE = "INFERENCE"
    ASSUMPTION = "ASSUMPTION"


class PremisePolarity(StrEnum):
    SUPPORTS = "SUPPORTS"
    OPPOSES = "OPPOSES"
    QUALIFIES = "QUALIFIES"


class SupportState(StrEnum):
    TRUE = "TRUE"
    FALSE = "FALSE"
    UNKNOWN = "UNKNOWN"


class ScopeRelevance(StrEnum):
    APPLICABLE = "APPLICABLE"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    UNKNOWN = "UNKNOWN"


class ThesisRole(StrEnum):
    PRIMARY = "PRIMARY"
    COUNTER = "COUNTER"


class ThesisSupport(StrEnum):
    SUPPORTED = "SUPPORTED"
    CONDITIONAL = "CONDITIONAL"
    REFUTED = "REFUTED"
    UNDETERMINED = "UNDETERMINED"


class ChallengeFamily(StrEnum):
    EVIDENCE_COVERAGE = "EVIDENCE_COVERAGE"
    SOURCE_BASIS = "SOURCE_BASIS"
    FRESHNESS = "FRESHNESS"
    ASSUMPTION_SUPPORT = "ASSUMPTION_SUPPORT"
    THESIS_TENSION = "THESIS_TENSION"
    RISK_CONSTRAINT = "RISK_CONSTRAINT"
    TIMING_MATURITY = "TIMING_MATURITY"
    BASELINE_DIVERGENCE = "BASELINE_DIVERGENCE"


class FindingSeverity(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class Materiality(StrEnum):
    NON_MATERIAL = "NON_MATERIAL"
    MATERIAL = "MATERIAL"
    HARD_CONSTRAINT = "HARD_CONSTRAINT"


class ChallengeStatus(StrEnum):
    UPHELD = "UPHELD"
    QUALIFIED = "QUALIFIED"
    RESOLVED = "RESOLVED"
    UNEVALUATED = "UNEVALUATED"


class ArbitrationDisposition(StrEnum):
    ADMITTED = "ADMITTED"
    REJECTED = "REJECTED"
    QUALIFIED = "QUALIFIED"
    UNRESOLVED = "UNRESOLVED"


class UncertaintyKind(StrEnum):
    KNOWN_LIMITATION = "KNOWN_LIMITATION"
    UNKNOWN = "UNKNOWN"


class EvidenceNeedStatus(StrEnum):
    PLACEHOLDER_ONLY = "PLACEHOLDER_ONLY"


class InvalidationKind(StrEnum):
    PREMISE_NO_LONGER_TRUE = "PREMISE_NO_LONGER_TRUE"
    ELIGIBLE_REVISION_CONTRADICTS = "ELIGIBLE_REVISION_CONTRADICTS"
    TIMING_CONDITION_RESOLVED = "TIMING_CONDITION_RESOLVED"
    RISK_CONSTRAINT_REMOVED = "RISK_CONSTRAINT_REMOVED"


class A4Disposition(StrEnum):
    NO_TRADE = "NO_TRADE"
    AVOID = "AVOID"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    ABSTAIN = "ABSTAIN"
    CONFLICTED = "CONFLICTED"
    WAIT = "WAIT"
    SUPPORTIVE = "SUPPORTIVE"


class A4ExecutionStatus(StrEnum):
    COMPLETE = "COMPLETE"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"


class FailureStage(StrEnum):
    INPUT_VALIDATION = "INPUT_VALIDATION"
    THESIS_CONSTRUCTION = "THESIS_CONSTRUCTION"
    CHALLENGER = "CHALLENGER"
    ARBITRATION = "ARBITRATION"
    OUTPUT_VALIDATION = "OUTPUT_VALIDATION"
    REPLAY = "REPLAY"


class A4FailureCode(StrEnum):
    CORRUPT_INPUT = "CORRUPT_INPUT"
    UNSUPPORTED_POLICY = "UNSUPPORTED_POLICY"
    CHALLENGER_FAILED = "CHALLENGER_FAILED"
    THESIS_CONSTRUCTION_FAILED = "THESIS_CONSTRUCTION_FAILED"
    ARBITRATION_FAILED = "ARBITRATION_FAILED"
    UNRESOLVED_REQUIRED_RULE = "UNRESOLVED_REQUIRED_RULE"
    OUTPUT_FINGERPRINT_FAILED = "OUTPUT_FINGERPRINT_FAILED"
    CAPTURE_INTEGRITY_FAILED = "CAPTURE_INTEGRITY_FAILED"


class A4ReplayMode(StrEnum):
    RECORDED = "RECORDED"
    DETERMINISTIC_VERIFICATION = "DETERMINISTIC_VERIFICATION"
    POLICY_COMPARISON = "POLICY_COMPARISON"

